import type { WordItem } from './words-database'

const getImageUrl = (keyword: string) => `https://picsum.photos/seed/${encodeURIComponent(keyword.replace(/\s+/g, '-'))}/400/300`

export const ADDITIONAL_BEGINNER_WORDS: WordItem[] = [
  // ============ MORE BEGINNER WORDS ============
  
  // More Food & Drinks
  { word: 'soup', arabic: 'حساء', example: 'I love hot soup in winter.', category: 'food', imageUrl: getImageUrl('soup bowl'), level: 'beginner' },
  { word: 'salad', arabic: 'سلطة', example: 'This salad is fresh and healthy.', category: 'food', imageUrl: getImageUrl('fresh salad'), level: 'beginner' },
  { word: 'sandwich', arabic: 'شطيرة', example: 'I made a cheese sandwich.', category: 'food', imageUrl: getImageUrl('sandwich food'), level: 'beginner' },
  { word: 'pasta', arabic: 'معكرونة', example: 'Pasta with tomato sauce is delicious.', category: 'food', imageUrl: getImageUrl('pasta italian'), level: 'beginner' },
  { word: 'fries', arabic: 'بطاطس مقلية', example: 'Kids love French fries.', category: 'food', imageUrl: getImageUrl('french fries'), level: 'beginner' },
  { word: 'ice cream', arabic: 'آيس كريم', example: 'Ice cream is cold and sweet.', category: 'food', imageUrl: getImageUrl('ice cream cone'), level: 'beginner' },
  { word: 'yogurt', arabic: 'زبادي', example: 'Yogurt is good for health.', category: 'food', imageUrl: getImageUrl('yogurt healthy'), level: 'beginner' },
  { word: 'honey', arabic: 'عسل', example: 'Honey is naturally sweet.', category: 'food', imageUrl: getImageUrl('honey jar'), level: 'beginner' },
  { word: 'butter', arabic: 'زبدة', example: 'Put butter on the bread.', category: 'food', imageUrl: getImageUrl('butter bread'), level: 'beginner' },
  { word: 'sugar', arabic: 'سكر', example: 'Add sugar to your tea.', category: 'food', imageUrl: getImageUrl('sugar sweet'), level: 'beginner' },
  { word: 'salt', arabic: 'ملح', example: 'Add a little salt to the food.', category: 'food', imageUrl: getImageUrl('salt cooking'), level: 'beginner' },
  { word: 'pepper', arabic: 'فلفل', example: 'Black pepper adds flavor.', category: 'food', imageUrl: getImageUrl('black pepper'), level: 'beginner' },
  { word: 'garlic', arabic: 'ثوم', example: 'Garlic has a strong smell.', category: 'food', imageUrl: getImageUrl('garlic cooking'), level: 'beginner' },
  { word: 'onion', arabic: 'بصل', example: 'Onions make you cry when cutting.', category: 'food', imageUrl: getImageUrl('onion vegetable'), level: 'beginner' },
  { word: 'tomato', arabic: 'طماطم', example: 'Tomatoes are red and juicy.', category: 'food', imageUrl: getImageUrl('tomato fresh'), level: 'beginner' },
  { word: 'potato', arabic: 'بطاطس', example: 'Potatoes can be cooked many ways.', category: 'food', imageUrl: getImageUrl('potato vegetable'), level: 'beginner' },
  { word: 'carrot', arabic: 'جزر', example: 'Carrots are orange and healthy.', category: 'food', imageUrl: getImageUrl('carrot vegetable'), level: 'beginner' },
  { word: 'cucumber', arabic: 'خيار', example: 'Cucumber is fresh in salads.', category: 'food', imageUrl: getImageUrl('cucumber fresh'), level: 'beginner' },
  { word: 'lettuce', arabic: 'خس', example: 'Lettuce is green and crispy.', category: 'food', imageUrl: getImageUrl('lettuce salad'), level: 'beginner' },
  { word: 'grape', arabic: 'عنب', example: 'Grapes can be green or red.', category: 'food', imageUrl: getImageUrl('grapes fruit'), level: 'beginner' },
  { word: 'strawberry', arabic: 'فراولة', example: 'Strawberries are sweet and red.', category: 'food', imageUrl: getImageUrl('strawberry fruit'), level: 'beginner' },
  { word: 'watermelon', arabic: 'بطيخ', example: 'Watermelon is great in summer.', category: 'food', imageUrl: getImageUrl('watermelon fruit'), level: 'beginner' },
  { word: 'mango', arabic: 'مانجو', example: 'Mango is a tropical fruit.', category: 'food', imageUrl: getImageUrl('mango fruit'), level: 'beginner' },
  { word: 'lemon', arabic: 'ليمون', example: 'Lemon is sour and yellow.', category: 'food', imageUrl: getImageUrl('lemon citrus'), level: 'beginner' },
  { word: 'pineapple', arabic: 'أناناس', example: 'Pineapple is sweet and tangy.', category: 'food', imageUrl: getImageUrl('pineapple tropical'), level: 'beginner' },
  
  // More Animals
  { word: 'tiger', arabic: 'نمر', example: 'The tiger is a powerful animal.', category: 'animals', imageUrl: getImageUrl('tiger wild'), level: 'beginner' },
  { word: 'giraffe', arabic: 'زرافة', example: 'The giraffe has a long neck.', category: 'animals', imageUrl: getImageUrl('giraffe africa'), level: 'beginner' },
  { word: 'zebra', arabic: 'حمار وحشي', example: 'Zebras have black and white stripes.', category: 'animals', imageUrl: getImageUrl('zebra stripes'), level: 'beginner' },
  { word: 'crocodile', arabic: 'تمساح', example: 'Crocodiles live in water.', category: 'animals', imageUrl: getImageUrl('crocodile reptile'), level: 'beginner' },
  { word: 'turtle', arabic: 'سلحفاة', example: 'Turtles move very slowly.', category: 'animals', imageUrl: getImageUrl('turtle slow'), level: 'beginner' },
  { word: 'frog', arabic: 'ضفدع', example: 'Frogs jump and live near water.', category: 'animals', imageUrl: getImageUrl('frog green'), level: 'beginner' },
  { word: 'duck', arabic: 'بطة', example: 'Ducks swim in the pond.', category: 'animals', imageUrl: getImageUrl('duck pond'), level: 'beginner' },
  { word: 'goose', arabic: 'إوزة', example: 'Geese fly in groups.', category: 'animals', imageUrl: getImageUrl('goose bird'), level: 'beginner' },
  { word: 'swan', arabic: 'بجعة', example: 'The swan is white and beautiful.', category: 'animals', imageUrl: getImageUrl('swan lake'), level: 'beginner' },
  { word: 'eagle', arabic: 'نسر', example: 'Eagles fly very high.', category: 'animals', imageUrl: getImageUrl('eagle flying'), level: 'beginner' },
  { word: 'owl', arabic: 'بومة', example: 'Owls are active at night.', category: 'animals', imageUrl: getImageUrl('owl night'), level: 'beginner' },
  { word: 'parrot', arabic: 'ببغاء', example: 'Parrots can talk like humans.', category: 'animals', imageUrl: getImageUrl('parrot colorful'), level: 'beginner' },
  { word: 'penguin', arabic: 'بطريق', example: 'Penguins live in cold places.', category: 'animals', imageUrl: getImageUrl('penguin arctic'), level: 'beginner' },
  { word: 'dolphin', arabic: 'دولفين', example: 'Dolphins are very intelligent.', category: 'animals', imageUrl: getImageUrl('dolphin ocean'), level: 'beginner' },
  { word: 'whale', arabic: 'حوت', example: 'Whales are the largest animals.', category: 'animals', imageUrl: getImageUrl('whale ocean'), level: 'beginner' },
  { word: 'shark', arabic: 'قرش', example: 'Sharks have sharp teeth.', category: 'animals', imageUrl: getImageUrl('shark sea'), level: 'beginner' },
  { word: 'octopus', arabic: 'أخطبوط', example: 'Octopuses have eight arms.', category: 'animals', imageUrl: getImageUrl('octopus sea'), level: 'beginner' },
  { word: 'crab', arabic: 'سلطعون', example: 'Crabs walk sideways.', category: 'animals', imageUrl: getImageUrl('crab beach'), level: 'beginner' },
  { word: 'bee', arabic: 'نحلة', example: 'Bees make honey.', category: 'animals', imageUrl: getImageUrl('bee flower'), level: 'beginner' },
  { word: 'ant', arabic: 'نملة', example: 'Ants work very hard.', category: 'animals', imageUrl: getImageUrl('ant insect'), level: 'beginner' },
  { word: 'spider', arabic: 'عنكبوت', example: 'Spiders make webs.', category: 'animals', imageUrl: getImageUrl('spider web'), level: 'beginner' },
  { word: 'mosquito', arabic: 'بعوضة', example: 'Mosquitoes bite at night.', category: 'animals', imageUrl: getImageUrl('mosquito insect'), level: 'beginner' },
  { word: 'fly', arabic: 'ذبابة', example: 'Flies are annoying insects.', category: 'animals', imageUrl: getImageUrl('fly insect'), level: 'beginner' },
  { word: 'mouse', arabic: 'فأر', example: 'Mice are small and fast.', category: 'animals', imageUrl: getImageUrl('mouse animal'), level: 'beginner' },
  { word: 'squirrel', arabic: 'سنجاب', example: 'Squirrels love nuts.', category: 'animals', imageUrl: getImageUrl('squirrel nuts'), level: 'beginner' },
  
  // More Home & Objects
  { word: 'sofa', arabic: 'أريكة', example: 'Sit on the comfortable sofa.', category: 'home', imageUrl: getImageUrl('sofa living room'), level: 'beginner' },
  { word: 'curtain', arabic: 'ستارة', example: 'Close the curtains please.', category: 'home', imageUrl: getImageUrl('curtain window'), level: 'beginner' },
  { word: 'mirror', arabic: 'مرآة', example: 'Look in the mirror.', category: 'home', imageUrl: getImageUrl('mirror reflection'), level: 'beginner' },
  { word: 'clock', arabic: 'ساعة حائط', example: 'The clock shows the time.', category: 'home', imageUrl: getImageUrl('wall clock'), level: 'beginner' },
  { word: 'television', arabic: 'تلفاز', example: 'We watch television at night.', category: 'home', imageUrl: getImageUrl('television tv'), level: 'beginner' },
  { word: 'refrigerator', arabic: 'ثلاجة', example: 'Keep food in the refrigerator.', category: 'home', imageUrl: getImageUrl('refrigerator kitchen'), level: 'beginner' },
  { word: 'oven', arabic: 'فرن', example: 'Bake bread in the oven.', category: 'home', imageUrl: getImageUrl('oven cooking'), level: 'beginner' },
  { word: 'microwave', arabic: 'ميكروويف', example: 'Heat food in the microwave.', category: 'home', imageUrl: getImageUrl('microwave kitchen'), level: 'beginner' },
  { word: 'sink', arabic: 'حوض', example: 'Wash dishes in the sink.', category: 'home', imageUrl: getImageUrl('sink kitchen'), level: 'beginner' },
  { word: 'towel', arabic: 'منشفة', example: 'Dry your hands with a towel.', category: 'home', imageUrl: getImageUrl('towel bathroom'), level: 'beginner' },
  { word: 'soap', arabic: 'صابون', example: 'Wash your hands with soap.', category: 'home', imageUrl: getImageUrl('soap clean'), level: 'beginner' },
  { word: 'toothbrush', arabic: 'فرشاة أسنان', example: 'Brush your teeth with a toothbrush.', category: 'home', imageUrl: getImageUrl('toothbrush dental'), level: 'beginner' },
  { word: 'pillow', arabic: 'وسادة', example: 'The pillow is soft.', category: 'home', imageUrl: getImageUrl('pillow bed'), level: 'beginner' },
  { word: 'blanket', arabic: 'بطانية', example: 'Cover yourself with a blanket.', category: 'home', imageUrl: getImageUrl('blanket warm'), level: 'beginner' },
  { word: 'carpet', arabic: 'سجادة', example: 'The carpet is soft and warm.', category: 'home', imageUrl: getImageUrl('carpet floor'), level: 'beginner' },
  { word: 'shelf', arabic: 'رف', example: 'Put the books on the shelf.', category: 'home', imageUrl: getImageUrl('shelf books'), level: 'beginner' },
  { word: 'wardrobe', arabic: 'خزانة ملابس', example: 'My clothes are in the wardrobe.', category: 'home', imageUrl: getImageUrl('wardrobe clothes'), level: 'beginner' },
  { word: 'drawer', arabic: 'درج', example: 'Open the drawer please.', category: 'home', imageUrl: getImageUrl('drawer furniture'), level: 'beginner' },
  { word: 'fan', arabic: 'مروحة', example: 'Turn on the fan when hot.', category: 'home', imageUrl: getImageUrl('fan cooling'), level: 'beginner' },
  { word: 'air conditioner', arabic: 'مكيف', example: 'The air conditioner cools the room.', category: 'home', imageUrl: getImageUrl('air conditioner'), level: 'beginner' },
  
  // More Body Parts
  { word: 'shoulder', arabic: 'كتف', example: 'My shoulder hurts a little.', category: 'body', imageUrl: getImageUrl('shoulder body'), level: 'beginner' },
  { word: 'elbow', arabic: 'مرفق', example: 'I hurt my elbow yesterday.', category: 'body', imageUrl: getImageUrl('elbow joint'), level: 'beginner' },
  { word: 'wrist', arabic: 'معصم', example: 'I wear a watch on my wrist.', category: 'body', imageUrl: getImageUrl('wrist watch'), level: 'beginner' },
  { word: 'knee', arabic: 'ركبة', example: 'My knee is injured.', category: 'body', imageUrl: getImageUrl('knee joint'), level: 'beginner' },
  { word: 'ankle', arabic: 'كاحل', example: 'I twisted my ankle.', category: 'body', imageUrl: getImageUrl('ankle foot'), level: 'beginner' },
  { word: 'toe', arabic: 'إصبع قدم', example: 'I have ten toes.', category: 'body', imageUrl: getImageUrl('toe foot'), level: 'beginner' },
  { word: 'thumb', arabic: 'إبهام', example: 'The thumb is very useful.', category: 'body', imageUrl: getImageUrl('thumb hand'), level: 'beginner' },
  { word: 'tongue', arabic: 'لسان', example: 'We taste food with our tongue.', category: 'body', imageUrl: getImageUrl('tongue taste'), level: 'beginner' },
  { word: 'tooth', arabic: 'سن', example: 'I lost a tooth yesterday.', category: 'body', imageUrl: getImageUrl('tooth dental'), level: 'beginner' },
  { word: 'lip', arabic: 'شفة', example: 'Her lips are red.', category: 'body', imageUrl: getImageUrl('lips face'), level: 'beginner' },
  { word: 'eyebrow', arabic: 'حاجب', example: 'She has thick eyebrows.', category: 'body', imageUrl: getImageUrl('eyebrow face'), level: 'beginner' },
  { word: 'chin', arabic: 'ذقن', example: 'He has a strong chin.', category: 'body', imageUrl: getImageUrl('chin face'), level: 'beginner' },
  { word: 'cheek', arabic: 'خد', example: 'Her cheeks are rosy.', category: 'body', imageUrl: getImageUrl('cheek face'), level: 'beginner' },
  { word: 'forehead', arabic: 'جبين', example: 'His forehead is wide.', category: 'body', imageUrl: getImageUrl('forehead face'), level: 'beginner' },
  { word: 'stomach', arabic: 'معدة', example: 'My stomach is full.', category: 'body', imageUrl: getImageUrl('stomach body'), level: 'beginner' },
  { word: 'chest', arabic: 'صدر', example: 'He has a strong chest.', category: 'body', imageUrl: getImageUrl('chest body'), level: 'beginner' },
  { word: 'brain', arabic: 'دماغ', example: 'The brain controls the body.', category: 'body', imageUrl: getImageUrl('brain thinking'), level: 'beginner' },
  { word: 'bone', arabic: 'عظم', example: 'Bones are very strong.', category: 'body', imageUrl: getImageUrl('bone skeleton'), level: 'beginner' },
  { word: 'muscle', arabic: 'عضلة', example: 'Exercise builds muscles.', category: 'body', imageUrl: getImageUrl('muscle fitness'), level: 'beginner' },
  { word: 'skin', arabic: 'جلد', example: 'Skin protects our body.', category: 'body', imageUrl: getImageUrl('skin care'), level: 'beginner' },
  
  // More Verbs
  { word: 'swim', arabic: 'يسبح', example: 'I swim in the pool.', category: 'verbs', imageUrl: getImageUrl('swimming pool'), level: 'beginner' },
  { word: 'jump', arabic: 'يقفز', example: 'The kids jump with joy.', category: 'verbs', imageUrl: getImageUrl('jumping joy'), level: 'beginner' },
  { word: 'dance', arabic: 'يرقص', example: 'We love to dance at parties.', category: 'verbs', imageUrl: getImageUrl('dancing party'), level: 'beginner' },
  { word: 'sing', arabic: 'يغني', example: 'She sings beautifully.', category: 'verbs', imageUrl: getImageUrl('singing music'), level: 'beginner' },
  { word: 'draw', arabic: 'يرسم', example: 'Children love to draw pictures.', category: 'verbs', imageUrl: getImageUrl('drawing art'), level: 'beginner' },
  { word: 'paint', arabic: 'يلون', example: 'Artists paint beautiful pictures.', category: 'verbs', imageUrl: getImageUrl('painting art'), level: 'beginner' },
  { word: 'cut', arabic: 'يقطع', example: 'Cut the paper with scissors.', category: 'verbs', imageUrl: getImageUrl('cutting scissors'), level: 'beginner' },
  { word: 'break', arabic: 'يكسر', example: 'Be careful not to break it.', category: 'verbs', imageUrl: getImageUrl('breaking glass'), level: 'beginner' },
  { word: 'fix', arabic: 'يصلح', example: 'He can fix the broken chair.', category: 'verbs', imageUrl: getImageUrl('fixing repair'), level: 'beginner' },
  { word: 'build', arabic: 'يبني', example: 'They build houses.', category: 'verbs', imageUrl: getImageUrl('building construction'), level: 'beginner' },
  { word: 'throw', arabic: 'يرمي', example: 'Throw the ball to me.', category: 'verbs', imageUrl: getImageUrl('throwing ball'), level: 'beginner' },
  { word: 'catch', arabic: 'يمسك', example: 'Catch the ball quickly.', category: 'verbs', imageUrl: getImageUrl('catching ball'), level: 'beginner' },
  { word: 'push', arabic: 'يدفع', example: 'Push the door to open it.', category: 'verbs', imageUrl: getImageUrl('pushing door'), level: 'beginner' },
  { word: 'pull', arabic: 'يسحب', example: 'Pull the handle gently.', category: 'verbs', imageUrl: getImageUrl('pulling rope'), level: 'beginner' },
  { word: 'carry', arabic: 'يحمل', example: 'Can you carry this bag?', category: 'verbs', imageUrl: getImageUrl('carrying bag'), level: 'beginner' },
  { word: 'hold', arabic: 'يمسك', example: 'Hold my hand please.', category: 'verbs', imageUrl: getImageUrl('holding hands'), level: 'beginner' },
  { word: 'touch', arabic: 'يلمس', example: 'Do not touch the hot stove.', category: 'verbs', imageUrl: getImageUrl('touching hand'), level: 'beginner' },
  { word: 'feel', arabic: 'يشعر', example: 'I feel happy today.', category: 'verbs', imageUrl: getImageUrl('feeling emotion'), level: 'beginner' },
  { word: 'think', arabic: 'يفكر', example: 'Think before you speak.', category: 'verbs', imageUrl: getImageUrl('thinking brain'), level: 'beginner' },
  { word: 'remember', arabic: 'يتذكر', example: 'I remember that day well.', category: 'verbs', imageUrl: getImageUrl('remembering memory'), level: 'beginner' },
  { word: 'forget', arabic: 'ينسى', example: 'Do not forget your keys.', category: 'verbs', imageUrl: getImageUrl('forgetting memory'), level: 'beginner' },
  { word: 'learn', arabic: 'يتعلم', example: 'I learn new words every day.', category: 'verbs', imageUrl: getImageUrl('learning study'), level: 'beginner' },
  { word: 'teach', arabic: 'يعلم', example: 'Teachers teach students.', category: 'verbs', imageUrl: getImageUrl('teaching classroom'), level: 'beginner' },
  { word: 'ask', arabic: 'يسأل', example: 'Ask if you have questions.', category: 'verbs', imageUrl: getImageUrl('asking question'), level: 'beginner' },
  { word: 'answer', arabic: 'يجيب', example: 'Answer the question please.', category: 'verbs', imageUrl: getImageUrl('answering reply'), level: 'beginner' },
  { word: 'wait', arabic: 'ينتظر', example: 'Please wait for me.', category: 'verbs', imageUrl: getImageUrl('waiting time'), level: 'beginner' },
  { word: 'start', arabic: 'يبدأ', example: 'Let us start the lesson.', category: 'verbs', imageUrl: getImageUrl('starting begin'), level: 'beginner' },
  { word: 'finish', arabic: 'ينهي', example: 'I will finish my homework.', category: 'verbs', imageUrl: getImageUrl('finishing complete'), level: 'beginner' },
  { word: 'try', arabic: 'يحاول', example: 'Try your best always.', category: 'verbs', imageUrl: getImageUrl('trying effort'), level: 'beginner' },
  { word: 'win', arabic: 'يفوز', example: 'Our team will win.', category: 'verbs', imageUrl: getImageUrl('winning victory'), level: 'beginner' },
  { word: 'lose', arabic: 'يخسر', example: 'Do not be sad if you lose.', category: 'verbs', imageUrl: getImageUrl('losing game'), level: 'beginner' },
  { word: 'smile', arabic: 'يبتسم', example: 'Always smile at others.', category: 'verbs', imageUrl: getImageUrl('smiling happy'), level: 'beginner' },
  { word: 'cry', arabic: 'يبكي', example: 'The baby started to cry.', category: 'verbs', imageUrl: getImageUrl('crying tears'), level: 'beginner' },
  { word: 'laugh', arabic: 'يضحك', example: 'We laugh at funny jokes.', category: 'verbs', imageUrl: getImageUrl('laughing happy'), level: 'beginner' },
  { word: 'shout', arabic: 'يصرخ', example: 'Do not shout in the library.', category: 'verbs', imageUrl: getImageUrl('shouting loud'), level: 'beginner' },
  { word: 'whisper', arabic: 'يهمس', example: 'Whisper so no one hears.', category: 'verbs', imageUrl: getImageUrl('whispering secret'), level: 'beginner' },
  
  // More Adjectives
  { word: 'tall', arabic: 'طويل', example: 'The building is very tall.', category: 'adjectives', imageUrl: getImageUrl('tall building'), level: 'beginner' },
  { word: 'short', arabic: 'قصير', example: 'The child is short.', category: 'adjectives', imageUrl: getImageUrl('short person'), level: 'beginner' },
  { word: 'long', arabic: 'طويل', example: 'She has long hair.', category: 'adjectives', imageUrl: getImageUrl('long hair'), level: 'beginner' },
  { word: 'wide', arabic: 'واسع', example: 'The road is wide.', category: 'adjectives', imageUrl: getImageUrl('wide road'), level: 'beginner' },
  { word: 'narrow', arabic: 'ضيق', example: 'The street is narrow.', category: 'adjectives', imageUrl: getImageUrl('narrow path'), level: 'beginner' },
  { word: 'thick', arabic: 'سميك', example: 'The book is thick.', category: 'adjectives', imageUrl: getImageUrl('thick book'), level: 'beginner' },
  { word: 'thin', arabic: 'رفيع', example: 'The paper is thin.', category: 'adjectives', imageUrl: getImageUrl('thin paper'), level: 'beginner' },
  { word: 'heavy', arabic: 'ثقيل', example: 'This box is heavy.', category: 'adjectives', imageUrl: getImageUrl('heavy weight'), level: 'beginner' },
  { word: 'light', arabic: 'خفيف', example: 'The feather is light.', category: 'adjectives', imageUrl: getImageUrl('light feather'), level: 'beginner' },
  { word: 'soft', arabic: 'ناعم', example: 'The pillow is soft.', category: 'adjectives', imageUrl: getImageUrl('soft pillow'), level: 'beginner' },
  { word: 'hard', arabic: 'صلب', example: 'The rock is hard.', category: 'adjectives', imageUrl: getImageUrl('hard rock'), level: 'beginner' },
  { word: 'wet', arabic: 'مبلل', example: 'The floor is wet.', category: 'adjectives', imageUrl: getImageUrl('wet rain'), level: 'beginner' },
  { word: 'dry', arabic: 'جاف', example: 'The desert is dry.', category: 'adjectives', imageUrl: getImageUrl('dry desert'), level: 'beginner' },
  { word: 'full', arabic: 'ممتلئ', example: 'The glass is full.', category: 'adjectives', imageUrl: getImageUrl('full glass'), level: 'beginner' },
  { word: 'empty', arabic: 'فارغ', example: 'The box is empty.', category: 'adjectives', imageUrl: getImageUrl('empty box'), level: 'beginner' },
  { word: 'loud', arabic: 'صاخب', example: 'The music is too loud.', category: 'adjectives', imageUrl: getImageUrl('loud music'), level: 'beginner' },
  { word: 'quiet', arabic: 'هادئ', example: 'The library is quiet.', category: 'adjectives', imageUrl: getImageUrl('quiet peaceful'), level: 'beginner' },
  { word: 'strong', arabic: 'قوي', example: 'He is very strong.', category: 'adjectives', imageUrl: getImageUrl('strong muscle'), level: 'beginner' },
  { word: 'weak', arabic: 'ضعيف', example: 'The signal is weak.', category: 'adjectives', imageUrl: getImageUrl('weak signal'), level: 'beginner' },
  { word: 'bright', arabic: 'ساطع', example: 'The sun is bright.', category: 'adjectives', imageUrl: getImageUrl('bright sun'), level: 'beginner' },
  { word: 'dark', arabic: 'مظلم', example: 'The room is dark.', category: 'adjectives', imageUrl: getImageUrl('dark night'), level: 'beginner' },
  { word: 'sweet', arabic: 'حلو', example: 'The candy is sweet.', category: 'adjectives', imageUrl: getImageUrl('sweet candy'), level: 'beginner' },
  { word: 'sour', arabic: 'حامض', example: 'Lemons are sour.', category: 'adjectives', imageUrl: getImageUrl('sour lemon'), level: 'beginner' },
  { word: 'bitter', arabic: 'مر', example: 'The medicine is bitter.', category: 'adjectives', imageUrl: getImageUrl('bitter medicine'), level: 'beginner' },
  { word: 'spicy', arabic: 'حار', example: 'This food is spicy.', category: 'adjectives', imageUrl: getImageUrl('spicy chili'), level: 'beginner' },
  { word: 'fresh', arabic: 'طازج', example: 'The bread is fresh.', category: 'adjectives', imageUrl: getImageUrl('fresh bread'), level: 'beginner' },
  { word: 'frozen', arabic: 'مجمد', example: 'The ice is frozen.', category: 'adjectives', imageUrl: getImageUrl('frozen ice'), level: 'beginner' },
  { word: 'young', arabic: 'صغير السن', example: 'The child is young.', category: 'adjectives', imageUrl: getImageUrl('young child'), level: 'beginner' },
  { word: 'sick', arabic: 'مريض', example: 'I feel sick today.', category: 'adjectives', imageUrl: getImageUrl('sick ill'), level: 'beginner' },
  { word: 'healthy', arabic: 'صحي', example: 'Eat healthy food.', category: 'adjectives', imageUrl: getImageUrl('healthy lifestyle'), level: 'beginner' },
  { word: 'tired', arabic: 'متعب', example: 'I am very tired.', category: 'adjectives', imageUrl: getImageUrl('tired sleepy'), level: 'beginner' },
  { word: 'hungry', arabic: 'جائع', example: 'I am hungry now.', category: 'adjectives', imageUrl: getImageUrl('hungry food'), level: 'beginner' },
  { word: 'thirsty', arabic: 'عطشان', example: 'I am thirsty for water.', category: 'adjectives', imageUrl: getImageUrl('thirsty water'), level: 'beginner' },
  { word: 'angry', arabic: 'غاضب', example: 'He looks angry.', category: 'adjectives', imageUrl: getImageUrl('angry face'), level: 'beginner' },
  { word: 'scared', arabic: 'خائف', example: 'The child is scared.', category: 'adjectives', imageUrl: getImageUrl('scared fear'), level: 'beginner' },
  { word: 'surprised', arabic: 'متفاجئ', example: 'I was surprised by the news.', category: 'adjectives', imageUrl: getImageUrl('surprised face'), level: 'beginner' },
  { word: 'excited', arabic: 'متحمس', example: 'I am excited about the trip.', category: 'adjectives', imageUrl: getImageUrl('excited happy'), level: 'beginner' },
  { word: 'bored', arabic: 'يشعر بالملل', example: 'I am bored at home.', category: 'adjectives', imageUrl: getImageUrl('bored person'), level: 'beginner' },
  { word: 'busy', arabic: 'مشغول', example: 'I am very busy today.', category: 'adjectives', imageUrl: getImageUrl('busy working'), level: 'beginner' },
  { word: 'free', arabic: 'فارغ / حر', example: 'Are you free tomorrow?', category: 'adjectives', imageUrl: getImageUrl('free time'), level: 'beginner' },
  
  // Places
  { word: 'park', arabic: 'حديقة عامة', example: 'Children play in the park.', category: 'places', imageUrl: getImageUrl('park playground'), level: 'beginner' },
  { word: 'hospital', arabic: 'مستشفى', example: 'The hospital helps sick people.', category: 'places', imageUrl: getImageUrl('hospital building'), level: 'beginner' },
  { word: 'restaurant', arabic: 'مطعم', example: 'We eat at the restaurant.', category: 'places', imageUrl: getImageUrl('restaurant dining'), level: 'beginner' },
  { word: 'supermarket', arabic: 'سوبرماركت', example: 'Buy groceries at the supermarket.', category: 'places', imageUrl: getImageUrl('supermarket shopping'), level: 'beginner' },
  { word: 'bank', arabic: 'بنك', example: 'I save money in the bank.', category: 'places', imageUrl: getImageUrl('bank building'), level: 'beginner' },
  { word: 'pharmacy', arabic: 'صيدلية', example: 'Buy medicine at the pharmacy.', category: 'places', imageUrl: getImageUrl('pharmacy medicine'), level: 'beginner' },
  { word: 'cinema', arabic: 'سينما', example: 'We watch movies at the cinema.', category: 'places', imageUrl: getImageUrl('cinema movie'), level: 'beginner' },
  { word: 'museum', arabic: 'متحف', example: 'The museum has old things.', category: 'places', imageUrl: getImageUrl('museum art'), level: 'beginner' },
  { word: 'zoo', arabic: 'حديقة حيوانات', example: 'Children love visiting the zoo.', category: 'places', imageUrl: getImageUrl('zoo animals'), level: 'beginner' },
  { word: 'stadium', arabic: 'ملعب', example: 'We watch football at the stadium.', category: 'places', imageUrl: getImageUrl('stadium sports'), level: 'beginner' },
  { word: 'mall', arabic: 'مركز تسوق', example: 'The mall has many shops.', category: 'places', imageUrl: getImageUrl('mall shopping'), level: 'beginner' },
  { word: 'hotel', arabic: 'فندق', example: 'We stay at the hotel.', category: 'places', imageUrl: getImageUrl('hotel room'), level: 'beginner' },
  { word: 'mosque', arabic: 'مسجد', example: 'People pray at the mosque.', category: 'places', imageUrl: getImageUrl('mosque prayer'), level: 'beginner' },
  { word: 'church', arabic: 'كنيسة', example: 'The church is beautiful.', category: 'places', imageUrl: getImageUrl('church building'), level: 'beginner' },
  { word: 'police station', arabic: 'مركز شرطة', example: 'Report crimes at the police station.', category: 'places', imageUrl: getImageUrl('police station'), level: 'beginner' },
  { word: 'fire station', arabic: 'محطة إطفاء', example: 'Firefighters work at the fire station.', category: 'places', imageUrl: getImageUrl('fire station'), level: 'beginner' },
  { word: 'post office', arabic: 'مكتب بريد', example: 'Send letters at the post office.', category: 'places', imageUrl: getImageUrl('post office mail'), level: 'beginner' },
  { word: 'bakery', arabic: 'مخبز', example: 'Fresh bread from the bakery.', category: 'places', imageUrl: getImageUrl('bakery bread'), level: 'beginner' },
  { word: 'bookstore', arabic: 'مكتبة كتب', example: 'Buy books at the bookstore.', category: 'places', imageUrl: getImageUrl('bookstore books'), level: 'beginner' },
  { word: 'gym', arabic: 'نادي رياضي', example: 'I exercise at the gym.', category: 'places', imageUrl: getImageUrl('gym fitness'), level: 'beginner' },
  
  // Sports & Activities
  { word: 'football', arabic: 'كرة القدم', example: 'Football is popular worldwide.', category: 'sports', imageUrl: getImageUrl('football soccer'), level: 'beginner' },
  { word: 'basketball', arabic: 'كرة السلة', example: 'He plays basketball well.', category: 'sports', imageUrl: getImageUrl('basketball court'), level: 'beginner' },
  { word: 'tennis', arabic: 'تنس', example: 'Tennis is a fun sport.', category: 'sports', imageUrl: getImageUrl('tennis court'), level: 'beginner' },
  { word: 'volleyball', arabic: 'كرة الطائرة', example: 'We play volleyball at the beach.', category: 'sports', imageUrl: getImageUrl('volleyball beach'), level: 'beginner' },
  { word: 'swimming', arabic: 'سباحة', example: 'Swimming is good exercise.', category: 'sports', imageUrl: getImageUrl('swimming pool'), level: 'beginner' },
  { word: 'running', arabic: 'جري', example: 'Running keeps you healthy.', category: 'sports', imageUrl: getImageUrl('running jogging'), level: 'beginner' },
  { word: 'cycling', arabic: 'ركوب الدراجة', example: 'Cycling is eco-friendly.', category: 'sports', imageUrl: getImageUrl('cycling bike'), level: 'beginner' },
  { word: 'boxing', arabic: 'ملاكمة', example: 'Boxing requires strength.', category: 'sports', imageUrl: getImageUrl('boxing sport'), level: 'beginner' },
  { word: 'golf', arabic: 'جولف', example: 'Golf is a relaxing sport.', category: 'sports', imageUrl: getImageUrl('golf course'), level: 'beginner' },
  { word: 'skiing', arabic: 'تزلج', example: 'Skiing is fun in winter.', category: 'sports', imageUrl: getImageUrl('skiing snow'), level: 'beginner' },
  { word: 'yoga', arabic: 'يوغا', example: 'Yoga helps relax the mind.', category: 'sports', imageUrl: getImageUrl('yoga meditation'), level: 'beginner' },
  { word: 'hiking', arabic: 'المشي لمسافات طويلة', example: 'Hiking in mountains is fun.', category: 'sports', imageUrl: getImageUrl('hiking mountain'), level: 'beginner' },
  { word: 'camping', arabic: 'تخييم', example: 'We go camping in summer.', category: 'sports', imageUrl: getImageUrl('camping tent'), level: 'beginner' },
  { word: 'fishing', arabic: 'صيد السمك', example: 'Fishing is very relaxing.', category: 'sports', imageUrl: getImageUrl('fishing rod'), level: 'beginner' },
  { word: 'horse riding', arabic: 'ركوب الخيل', example: 'Horse riding is exciting.', category: 'sports', imageUrl: getImageUrl('horse riding'), level: 'beginner' },
  
  // Weather
  { word: 'sunny', arabic: 'مشمس', example: 'Today is sunny and warm.', category: 'weather', imageUrl: getImageUrl('sunny day'), level: 'beginner' },
  { word: 'cloudy', arabic: 'غائم', example: 'The sky is cloudy today.', category: 'weather', imageUrl: getImageUrl('cloudy sky'), level: 'beginner' },
  { word: 'rainy', arabic: 'ماطر', example: 'It is rainy outside.', category: 'weather', imageUrl: getImageUrl('rainy weather'), level: 'beginner' },
  { word: 'windy', arabic: 'عاصف', example: 'It is very windy today.', category: 'weather', imageUrl: getImageUrl('windy weather'), level: 'beginner' },
  { word: 'snowy', arabic: 'ثلجي', example: 'The winter is snowy.', category: 'weather', imageUrl: getImageUrl('snowy winter'), level: 'beginner' },
  { word: 'foggy', arabic: 'ضبابي', example: 'The morning is foggy.', category: 'weather', imageUrl: getImageUrl('foggy morning'), level: 'beginner' },
  { word: 'stormy', arabic: 'عاصف', example: 'The weather is stormy.', category: 'weather', imageUrl: getImageUrl('stormy weather'), level: 'beginner' },
  { word: 'warm', arabic: 'دافئ', example: 'Spring weather is warm.', category: 'weather', imageUrl: getImageUrl('warm spring'), level: 'beginner' },
  { word: 'cool', arabic: 'بارد نوعا ما', example: 'The evening is cool.', category: 'weather', imageUrl: getImageUrl('cool evening'), level: 'beginner' },
  { word: 'humid', arabic: 'رطب', example: 'Summer is hot and humid.', category: 'weather', imageUrl: getImageUrl('humid weather'), level: 'beginner' },
  
  // Days & Months
  { word: 'Monday', arabic: 'الاثنين', example: 'Monday is the first workday.', category: 'time', imageUrl: getImageUrl('monday calendar'), level: 'beginner' },
  { word: 'Tuesday', arabic: 'الثلاثاء', example: 'We have class on Tuesday.', category: 'time', imageUrl: getImageUrl('tuesday calendar'), level: 'beginner' },
  { word: 'Wednesday', arabic: 'الأربعاء', example: 'Wednesday is the middle of the week.', category: 'time', imageUrl: getImageUrl('wednesday calendar'), level: 'beginner' },
  { word: 'Thursday', arabic: 'الخميس', example: 'Thursday is almost the weekend.', category: 'time', imageUrl: getImageUrl('thursday calendar'), level: 'beginner' },
  { word: 'Friday', arabic: 'الجمعة', example: 'Friday is a holiday for many.', category: 'time', imageUrl: getImageUrl('friday prayer'), level: 'beginner' },
  { word: 'Saturday', arabic: 'السبت', example: 'Saturday is for relaxing.', category: 'time', imageUrl: getImageUrl('saturday weekend'), level: 'beginner' },
  { word: 'Sunday', arabic: 'الأحد', example: 'Sunday is a family day.', category: 'time', imageUrl: getImageUrl('sunday family'), level: 'beginner' },
  { word: 'January', arabic: 'يناير', example: 'January is the first month.', category: 'time', imageUrl: getImageUrl('january winter'), level: 'beginner' },
  { word: 'February', arabic: 'فبراير', example: 'February is short.', category: 'time', imageUrl: getImageUrl('february valentine'), level: 'beginner' },
  { word: 'March', arabic: 'مارس', example: 'March brings spring.', category: 'time', imageUrl: getImageUrl('march spring'), level: 'beginner' },
  { word: 'April', arabic: 'أبريل', example: 'April has nice weather.', category: 'time', imageUrl: getImageUrl('april spring'), level: 'beginner' },
  { word: 'May', arabic: 'مايو', example: 'May flowers bloom.', category: 'time', imageUrl: getImageUrl('may flowers'), level: 'beginner' },
  { word: 'June', arabic: 'يونيو', example: 'June starts summer.', category: 'time', imageUrl: getImageUrl('june summer'), level: 'beginner' },
  { word: 'July', arabic: 'يوليو', example: 'July is very hot.', category: 'time', imageUrl: getImageUrl('july summer'), level: 'beginner' },
  { word: 'August', arabic: 'أغسطس', example: 'August is summer vacation.', category: 'time', imageUrl: getImageUrl('august beach'), level: 'beginner' },
  { word: 'September', arabic: 'سبتمبر', example: 'September starts school.', category: 'time', imageUrl: getImageUrl('september autumn'), level: 'beginner' },
  { word: 'October', arabic: 'أكتوبر', example: 'October leaves change color.', category: 'time', imageUrl: getImageUrl('october autumn'), level: 'beginner' },
  { word: 'November', arabic: 'نوفمبر', example: 'November is getting cold.', category: 'time', imageUrl: getImageUrl('november autumn'), level: 'beginner' },
  { word: 'December', arabic: 'ديسمبر', example: 'December brings holidays.', category: 'time', imageUrl: getImageUrl('december winter'), level: 'beginner' },
]

export const ADDITIONAL_INTERMEDIATE_WORDS: WordItem[] = [
  // ============ MORE INTERMEDIATE WORDS ============
  
  // Relationships & Social
  { word: 'friendship', arabic: 'صداقة', example: 'Friendship is very valuable.', category: 'relationships', imageUrl: getImageUrl('friendship friends'), level: 'intermediate' },
  { word: 'relationship', arabic: 'علاقة', example: 'Good relationships need trust.', category: 'relationships', imageUrl: getImageUrl('relationship couple'), level: 'intermediate' },
  { word: 'colleague', arabic: 'زميل عمل', example: 'My colleague helped me today.', category: 'relationships', imageUrl: getImageUrl('colleague office'), level: 'intermediate' },
  { word: 'neighbor', arabic: 'جار', example: 'My neighbor is very friendly.', category: 'relationships', imageUrl: getImageUrl('neighbor community'), level: 'intermediate' },
  { word: 'stranger', arabic: 'غريب', example: 'Do not talk to strangers.', category: 'relationships', imageUrl: getImageUrl('stranger person'), level: 'intermediate' },
  { word: 'partner', arabic: 'شريك', example: 'My business partner is reliable.', category: 'relationships', imageUrl: getImageUrl('partner business'), level: 'intermediate' },
  { word: 'acquaintance', arabic: 'معرفة', example: 'He is just an acquaintance.', category: 'relationships', imageUrl: getImageUrl('acquaintance meeting'), level: 'intermediate' },
  { word: 'companion', arabic: 'رفيق', example: 'A good companion is rare.', category: 'relationships', imageUrl: getImageUrl('companion friend'), level: 'intermediate' },
  { word: 'teammate', arabic: 'زميل فريق', example: 'My teammates support each other.', category: 'relationships', imageUrl: getImageUrl('teammate sports'), level: 'intermediate' },
  { word: 'classmate', arabic: 'زميل صف', example: 'My classmate is smart.', category: 'relationships', imageUrl: getImageUrl('classmate school'), level: 'intermediate' },
  
  // Communication Verbs
  { word: 'communicate', arabic: 'يتواصل', example: 'We communicate through email.', category: 'communication', imageUrl: getImageUrl('communication talk'), level: 'intermediate' },
  { word: 'discuss', arabic: 'يناقش', example: 'Let us discuss the problem.', category: 'communication', imageUrl: getImageUrl('discussion meeting'), level: 'intermediate' },
  { word: 'explain', arabic: 'يشرح', example: 'Please explain the lesson again.', category: 'communication', imageUrl: getImageUrl('explaining teaching'), level: 'intermediate' },
  { word: 'describe', arabic: 'يصف', example: 'Describe what you saw.', category: 'communication', imageUrl: getImageUrl('describing words'), level: 'intermediate' },
  { word: 'suggest', arabic: 'يقترح', example: 'I suggest we take a break.', category: 'communication', imageUrl: getImageUrl('suggestion idea'), level: 'intermediate' },
  { word: 'recommend', arabic: 'يوصي', example: 'I recommend this restaurant.', category: 'communication', imageUrl: getImageUrl('recommendation advice'), level: 'intermediate' },
  { word: 'complain', arabic: 'يشتكي', example: 'Do not complain too much.', category: 'communication', imageUrl: getImageUrl('complaining upset'), level: 'intermediate' },
  { word: 'apologize', arabic: 'يعتذر', example: 'I apologize for being late.', category: 'communication', imageUrl: getImageUrl('apologizing sorry'), level: 'intermediate' },
  { word: 'appreciate', arabic: 'يقدر', example: 'I appreciate your help.', category: 'communication', imageUrl: getImageUrl('appreciation thanks'), level: 'intermediate' },
  { word: 'congratulate', arabic: 'يهنئ', example: 'Congratulate him on his success.', category: 'communication', imageUrl: getImageUrl('congratulation celebration'), level: 'intermediate' },
  { word: 'encourage', arabic: 'يشجع', example: 'Teachers encourage students.', category: 'communication', imageUrl: getImageUrl('encouragement support'), level: 'intermediate' },
  { word: 'convince', arabic: 'يقنع', example: 'He convinced me to join.', category: 'communication', imageUrl: getImageUrl('convincing persuade'), level: 'intermediate' },
  { word: 'argue', arabic: 'يجادل', example: 'Do not argue with others.', category: 'communication', imageUrl: getImageUrl('arguing debate'), level: 'intermediate' },
  { word: 'agree', arabic: 'يوافق', example: 'I agree with your opinion.', category: 'communication', imageUrl: getImageUrl('agreement handshake'), level: 'intermediate' },
  { word: 'disagree', arabic: 'يختلف', example: 'I disagree with that idea.', category: 'communication', imageUrl: getImageUrl('disagreement debate'), level: 'intermediate' },
  
  // Work & Career
  { word: 'interview', arabic: 'مقابلة', example: 'I have a job interview tomorrow.', category: 'career', imageUrl: getImageUrl('job interview'), level: 'intermediate' },
  { word: 'resume', arabic: 'سيرة ذاتية', example: 'Update your resume regularly.', category: 'career', imageUrl: getImageUrl('resume document'), level: 'intermediate' },
  { word: 'promotion', arabic: 'ترقية', example: 'She got a promotion at work.', category: 'career', imageUrl: getImageUrl('promotion success'), level: 'intermediate' },
  { word: 'retire', arabic: 'يتقاعد', example: 'He will retire next year.', category: 'career', imageUrl: getImageUrl('retirement elderly'), level: 'intermediate' },
  { word: 'overtime', arabic: 'وقت إضافي', example: 'I worked overtime yesterday.', category: 'career', imageUrl: getImageUrl('overtime work'), level: 'intermediate' },
  { word: 'colleague', arabic: 'زميل', example: 'My colleagues are helpful.', category: 'career', imageUrl: getImageUrl('colleagues office'), level: 'intermediate' },
  { word: 'supervisor', arabic: 'مشرف', example: 'Talk to your supervisor.', category: 'career', imageUrl: getImageUrl('supervisor boss'), level: 'intermediate' },
  { word: 'shift', arabic: 'وردية', example: 'I work the night shift.', category: 'career', imageUrl: getImageUrl('work shift'), level: 'intermediate' },
  { word: 'vacation', arabic: 'إجازة', example: 'I need a vacation soon.', category: 'career', imageUrl: getImageUrl('vacation holiday'), level: 'intermediate' },
  { word: 'resign', arabic: 'يستقيل', example: 'He decided to resign.', category: 'career', imageUrl: getImageUrl('resignation letter'), level: 'intermediate' },
  { word: 'hire', arabic: 'يوظف', example: 'We need to hire new staff.', category: 'career', imageUrl: getImageUrl('hiring employee'), level: 'intermediate' },
  { word: 'training', arabic: 'تدريب', example: 'New employees need training.', category: 'career', imageUrl: getImageUrl('training workshop'), level: 'intermediate' },
  { word: 'experience', arabic: 'خبرة', example: 'Experience is very important.', category: 'career', imageUrl: getImageUrl('experience professional'), level: 'intermediate' },
  { word: 'qualification', arabic: 'مؤهل', example: 'List your qualifications.', category: 'career', imageUrl: getImageUrl('qualification certificate'), level: 'intermediate' },
  { word: 'responsibility', arabic: 'مسؤولية', example: 'Take responsibility for your work.', category: 'career', imageUrl: getImageUrl('responsibility duty'), level: 'intermediate' },
  
  // Education & Learning
  { word: 'university', arabic: 'جامعة', example: 'I study at the university.', category: 'education', imageUrl: getImageUrl('university campus'), level: 'intermediate' },
  { word: 'degree', arabic: 'شهادة', example: 'She has a masters degree.', category: 'education', imageUrl: getImageUrl('degree graduation'), level: 'intermediate' },
  { word: 'diploma', arabic: 'دبلوم', example: 'He earned his diploma.', category: 'education', imageUrl: getImageUrl('diploma certificate'), level: 'intermediate' },
  { word: 'scholarship', arabic: 'منحة دراسية', example: 'She won a scholarship.', category: 'education', imageUrl: getImageUrl('scholarship student'), level: 'intermediate' },
  { word: 'tuition', arabic: 'رسوم دراسية', example: 'Tuition fees are expensive.', category: 'education', imageUrl: getImageUrl('tuition payment'), level: 'intermediate' },
  { word: 'semester', arabic: 'فصل دراسي', example: 'The semester ends in June.', category: 'education', imageUrl: getImageUrl('semester calendar'), level: 'intermediate' },
  { word: 'lecture', arabic: 'محاضرة', example: 'The lecture was interesting.', category: 'education', imageUrl: getImageUrl('lecture class'), level: 'intermediate' },
  { word: 'assignment', arabic: 'واجب', example: 'Submit your assignment on time.', category: 'education', imageUrl: getImageUrl('assignment homework'), level: 'intermediate' },
  { word: 'grade', arabic: 'درجة', example: 'I got a good grade.', category: 'education', imageUrl: getImageUrl('grade score'), level: 'intermediate' },
  { word: 'curriculum', arabic: 'منهج دراسي', example: 'The curriculum was updated.', category: 'education', imageUrl: getImageUrl('curriculum study'), level: 'intermediate' },
  { word: 'research', arabic: 'بحث', example: 'Research takes time.', category: 'education', imageUrl: getImageUrl('research study'), level: 'intermediate' },
  { word: 'thesis', arabic: 'أطروحة', example: 'Write your thesis carefully.', category: 'education', imageUrl: getImageUrl('thesis paper'), level: 'intermediate' },
  { word: 'major', arabic: 'تخصص رئيسي', example: 'My major is engineering.', category: 'education', imageUrl: getImageUrl('major study'), level: 'intermediate' },
  { word: 'minor', arabic: 'تخصص فرعي', example: 'My minor is economics.', category: 'education', imageUrl: getImageUrl('minor study'), level: 'intermediate' },
  { word: 'tutorial', arabic: 'درس تعليمي', example: 'Watch the online tutorial.', category: 'education', imageUrl: getImageUrl('tutorial learning'), level: 'intermediate' },
  
  // Shopping & Commerce
  { word: 'discount', arabic: 'خصم', example: 'There is a 20% discount.', category: 'shopping', imageUrl: getImageUrl('discount sale'), level: 'intermediate' },
  { word: 'receipt', arabic: 'إيصال', example: 'Keep the receipt safe.', category: 'shopping', imageUrl: getImageUrl('receipt payment'), level: 'intermediate' },
  { word: 'refund', arabic: 'استرداد', example: 'I want a refund please.', category: 'shopping', imageUrl: getImageUrl('refund money'), level: 'intermediate' },
  { word: 'exchange', arabic: 'استبدال', example: 'Can I exchange this item?', category: 'shopping', imageUrl: getImageUrl('exchange shopping'), level: 'intermediate' },
  { word: 'warranty', arabic: 'ضمان', example: 'The warranty is one year.', category: 'shopping', imageUrl: getImageUrl('warranty guarantee'), level: 'intermediate' },
  { word: 'cashier', arabic: 'أمين صندوق', example: 'Pay the cashier.', category: 'shopping', imageUrl: getImageUrl('cashier checkout'), level: 'intermediate' },
  { word: 'checkout', arabic: 'الدفع', example: 'Go to the checkout counter.', category: 'shopping', imageUrl: getImageUrl('checkout counter'), level: 'intermediate' },
  { word: 'bargain', arabic: 'صفقة', example: 'That was a good bargain.', category: 'shopping', imageUrl: getImageUrl('bargain deal'), level: 'intermediate' },
  { word: 'brand', arabic: 'علامة تجارية', example: 'Which brand do you prefer?', category: 'shopping', imageUrl: getImageUrl('brand logo'), level: 'intermediate' },
  { word: 'quality', arabic: 'جودة', example: 'Quality is more important.', category: 'shopping', imageUrl: getImageUrl('quality product'), level: 'intermediate' },
  { word: 'quantity', arabic: 'كمية', example: 'Order the right quantity.', category: 'shopping', imageUrl: getImageUrl('quantity number'), level: 'intermediate' },
  { word: 'delivery', arabic: 'توصيل', example: 'Free delivery available.', category: 'shopping', imageUrl: getImageUrl('delivery shipping'), level: 'intermediate' },
  { word: 'customer', arabic: 'زبون', example: 'The customer is always right.', category: 'shopping', imageUrl: getImageUrl('customer service'), level: 'intermediate' },
  { word: 'order', arabic: 'طلب', example: 'Place your order online.', category: 'shopping', imageUrl: getImageUrl('order shopping'), level: 'intermediate' },
  { word: 'purchase', arabic: 'شراء', example: 'Complete your purchase.', category: 'shopping', imageUrl: getImageUrl('purchase buying'), level: 'intermediate' },
  
  // Food & Cooking
  { word: 'recipe', arabic: 'وصفة', example: 'Follow the recipe carefully.', category: 'cooking', imageUrl: getImageUrl('recipe cooking'), level: 'intermediate' },
  { word: 'ingredient', arabic: 'مكون', example: 'List all the ingredients.', category: 'cooking', imageUrl: getImageUrl('ingredients food'), level: 'intermediate' },
  { word: 'boil', arabic: 'يغلي', example: 'Boil water for tea.', category: 'cooking', imageUrl: getImageUrl('boiling water'), level: 'intermediate' },
  { word: 'fry', arabic: 'يقلي', example: 'Fry the eggs in a pan.', category: 'cooking', imageUrl: getImageUrl('frying pan'), level: 'intermediate' },
  { word: 'bake', arabic: 'يخبز', example: 'Bake the cake for an hour.', category: 'cooking', imageUrl: getImageUrl('baking oven'), level: 'intermediate' },
  { word: 'grill', arabic: 'يشوي', example: 'Grill the meat well.', category: 'cooking', imageUrl: getImageUrl('grilling barbecue'), level: 'intermediate' },
  { word: 'roast', arabic: 'يحمص', example: 'Roast the chicken perfectly.', category: 'cooking', imageUrl: getImageUrl('roasting oven'), level: 'intermediate' },
  { word: 'steam', arabic: 'يطهو بالبخار', example: 'Steam the vegetables.', category: 'cooking', imageUrl: getImageUrl('steaming vegetables'), level: 'intermediate' },
  { word: 'chop', arabic: 'يقطع', example: 'Chop the onions finely.', category: 'cooking', imageUrl: getImageUrl('chopping vegetables'), level: 'intermediate' },
  { word: 'mix', arabic: 'يخلط', example: 'Mix the ingredients together.', category: 'cooking', imageUrl: getImageUrl('mixing bowl'), level: 'intermediate' },
  { word: 'stir', arabic: 'يحرك', example: 'Stir the soup constantly.', category: 'cooking', imageUrl: getImageUrl('stirring pot'), level: 'intermediate' },
  { word: 'taste', arabic: 'يتذوق', example: 'Taste the food before serving.', category: 'cooking', imageUrl: getImageUrl('tasting food'), level: 'intermediate' },
  { word: 'season', arabic: 'يتبل', example: 'Season with salt and pepper.', category: 'cooking', imageUrl: getImageUrl('seasoning spices'), level: 'intermediate' },
  { word: 'serve', arabic: 'يقدم', example: 'Serve the food hot.', category: 'cooking', imageUrl: getImageUrl('serving food'), level: 'intermediate' },
  { word: 'appetizer', arabic: 'مقبلات', example: 'Start with an appetizer.', category: 'cooking', imageUrl: getImageUrl('appetizer food'), level: 'intermediate' },
  
  // Entertainment & Media
  { word: 'entertainment', arabic: 'ترفيه', example: 'Entertainment is important.', category: 'entertainment', imageUrl: getImageUrl('entertainment fun'), level: 'intermediate' },
  { word: 'movie', arabic: 'فيلم', example: 'Let us watch a movie.', category: 'entertainment', imageUrl: getImageUrl('movie cinema'), level: 'intermediate' },
  { word: 'concert', arabic: 'حفلة موسيقية', example: 'The concert was amazing.', category: 'entertainment', imageUrl: getImageUrl('concert music'), level: 'intermediate' },
  { word: 'theater', arabic: 'مسرح', example: 'We went to the theater.', category: 'entertainment', imageUrl: getImageUrl('theater stage'), level: 'intermediate' },
  { word: 'drama', arabic: 'دراما', example: 'I like watching drama.', category: 'entertainment', imageUrl: getImageUrl('drama acting'), level: 'intermediate' },
  { word: 'comedy', arabic: 'كوميديا', example: 'Comedy makes people laugh.', category: 'entertainment', imageUrl: getImageUrl('comedy funny'), level: 'intermediate' },
  { word: 'documentary', arabic: 'وثائقي', example: 'Watch this documentary.', category: 'entertainment', imageUrl: getImageUrl('documentary film'), level: 'intermediate' },
  { word: 'novel', arabic: 'رواية', example: 'I finished reading the novel.', category: 'entertainment', imageUrl: getImageUrl('novel book'), level: 'intermediate' },
  { word: 'poetry', arabic: 'شعر', example: 'She loves writing poetry.', category: 'entertainment', imageUrl: getImageUrl('poetry book'), level: 'intermediate' },
  { word: 'lyrics', arabic: 'كلمات أغنية', example: 'Learn the song lyrics.', category: 'entertainment', imageUrl: getImageUrl('lyrics music'), level: 'intermediate' },
  { word: 'episode', arabic: 'حلقة', example: 'Watch the next episode.', category: 'entertainment', imageUrl: getImageUrl('episode series'), level: 'intermediate' },
  { word: 'series', arabic: 'مسلسل', example: 'This series is exciting.', category: 'entertainment', imageUrl: getImageUrl('series tv'), level: 'intermediate' },
  { word: 'audience', arabic: 'جمهور', example: 'The audience applauded.', category: 'entertainment', imageUrl: getImageUrl('audience crowd'), level: 'intermediate' },
  { word: 'celebrity', arabic: 'مشهور', example: 'She is a famous celebrity.', category: 'entertainment', imageUrl: getImageUrl('celebrity famous'), level: 'intermediate' },
  { word: 'performance', arabic: 'أداء', example: 'Great performance by the actor.', category: 'entertainment', imageUrl: getImageUrl('performance stage'), level: 'intermediate' },
  
  // Nature & Environment
  { word: 'waterfall', arabic: 'شلال', example: 'The waterfall is beautiful.', category: 'nature', imageUrl: getImageUrl('waterfall nature'), level: 'intermediate' },
  { word: 'volcano', arabic: 'بركان', example: 'The volcano erupted yesterday.', category: 'nature', imageUrl: getImageUrl('volcano eruption'), level: 'intermediate' },
  { word: 'earthquake', arabic: 'زلزال', example: 'The earthquake was strong.', category: 'nature', imageUrl: getImageUrl('earthquake disaster'), level: 'intermediate' },
  { word: 'flood', arabic: 'فيضان', example: 'The flood damaged homes.', category: 'nature', imageUrl: getImageUrl('flood water'), level: 'intermediate' },
  { word: 'drought', arabic: 'جفاف', example: 'The drought affected crops.', category: 'nature', imageUrl: getImageUrl('drought dry'), level: 'intermediate' },
  { word: 'hurricane', arabic: 'إعصار', example: 'The hurricane was destructive.', category: 'nature', imageUrl: getImageUrl('hurricane storm'), level: 'intermediate' },
  { word: 'thunder', arabic: 'رعد', example: 'Thunder sounds scary.', category: 'nature', imageUrl: getImageUrl('thunder storm'), level: 'intermediate' },
  { word: 'lightning', arabic: 'برق', example: 'Lightning lit up the sky.', category: 'nature', imageUrl: getImageUrl('lightning storm'), level: 'intermediate' },
  { word: 'rainbow', arabic: 'قوس قزح', example: 'The rainbow appeared after rain.', category: 'nature', imageUrl: getImageUrl('rainbow sky'), level: 'intermediate' },
  { word: 'sunset', arabic: 'غروب الشمس', example: 'The sunset is gorgeous.', category: 'nature', imageUrl: getImageUrl('sunset sky'), level: 'intermediate' },
  { word: 'sunrise', arabic: 'شروق الشمس', example: 'Wake up for the sunrise.', category: 'nature', imageUrl: getImageUrl('sunrise morning'), level: 'intermediate' },
  { word: 'cave', arabic: 'كهف', example: 'Explore the dark cave.', category: 'nature', imageUrl: getImageUrl('cave dark'), level: 'intermediate' },
  { word: 'desert', arabic: 'صحراء', example: 'The desert is very hot.', category: 'nature', imageUrl: getImageUrl('desert sand'), level: 'intermediate' },
  { word: 'valley', arabic: 'وادي', example: 'The valley is green.', category: 'nature', imageUrl: getImageUrl('valley green'), level: 'intermediate' },
  { word: 'cliff', arabic: 'منحدر', example: 'Stand away from the cliff.', category: 'nature', imageUrl: getImageUrl('cliff mountain'), level: 'intermediate' },
  
  // Personality Traits
  { word: 'honest', arabic: 'صادق', example: 'Always be honest.', category: 'personality', imageUrl: getImageUrl('honest person'), level: 'intermediate' },
  { word: 'loyal', arabic: 'مخلص', example: 'A loyal friend is rare.', category: 'personality', imageUrl: getImageUrl('loyal friendship'), level: 'intermediate' },
  { word: 'patient', arabic: 'صبور', example: 'Teachers must be patient.', category: 'personality', imageUrl: getImageUrl('patient waiting'), level: 'intermediate' },
  { word: 'generous', arabic: 'كريم', example: 'She is very generous.', category: 'personality', imageUrl: getImageUrl('generous giving'), level: 'intermediate' },
  { word: 'ambitious', arabic: 'طموح', example: 'Ambitious people succeed.', category: 'personality', imageUrl: getImageUrl('ambitious success'), level: 'intermediate' },
  { word: 'humble', arabic: 'متواضع', example: 'Stay humble always.', category: 'personality', imageUrl: getImageUrl('humble modest'), level: 'intermediate' },
  { word: 'creative', arabic: 'مبدع', example: 'Artists are creative.', category: 'personality', imageUrl: getImageUrl('creative art'), level: 'intermediate' },
  { word: 'organized', arabic: 'منظم', example: 'She is very organized.', category: 'personality', imageUrl: getImageUrl('organized tidy'), level: 'intermediate' },
  { word: 'flexible', arabic: 'مرن', example: 'Be flexible with plans.', category: 'personality', imageUrl: getImageUrl('flexible adaptable'), level: 'intermediate' },
  { word: 'reliable', arabic: 'موثوق', example: 'He is a reliable worker.', category: 'personality', imageUrl: getImageUrl('reliable trustworthy'), level: 'intermediate' },
  { word: 'independent', arabic: 'مستقل', example: 'She is very independent.', category: 'personality', imageUrl: getImageUrl('independent person'), level: 'intermediate' },
  { word: 'sensitive', arabic: 'حساس', example: 'He is quite sensitive.', category: 'personality', imageUrl: getImageUrl('sensitive emotional'), level: 'intermediate' },
  { word: 'stubborn', arabic: 'عنيد', example: 'Do not be stubborn.', category: 'personality', imageUrl: getImageUrl('stubborn person'), level: 'intermediate' },
  { word: 'shy', arabic: 'خجول', example: 'She is a bit shy.', category: 'personality', imageUrl: getImageUrl('shy person'), level: 'intermediate' },
  { word: 'outgoing', arabic: 'اجتماعي', example: 'He is very outgoing.', category: 'personality', imageUrl: getImageUrl('outgoing social'), level: 'intermediate' },
  
  // More Technology
  { word: 'smartphone', arabic: 'هاتف ذكي', example: 'Everyone has a smartphone.', category: 'technology', imageUrl: getImageUrl('smartphone mobile'), level: 'intermediate' },
  { word: 'tablet', arabic: 'جهاز لوحي', example: 'Read books on the tablet.', category: 'technology', imageUrl: getImageUrl('tablet device'), level: 'intermediate' },
  { word: 'laptop', arabic: 'حاسوب محمول', example: 'Bring your laptop to class.', category: 'technology', imageUrl: getImageUrl('laptop computer'), level: 'intermediate' },
  { word: 'charger', arabic: 'شاحن', example: 'I forgot my phone charger.', category: 'technology', imageUrl: getImageUrl('charger phone'), level: 'intermediate' },
  { word: 'battery', arabic: 'بطارية', example: 'The battery is low.', category: 'technology', imageUrl: getImageUrl('battery power'), level: 'intermediate' },
  { word: 'update', arabic: 'تحديث', example: 'Update your software.', category: 'technology', imageUrl: getImageUrl('update software'), level: 'intermediate' },
  { word: 'backup', arabic: 'نسخة احتياطية', example: 'Make a backup of your files.', category: 'technology', imageUrl: getImageUrl('backup data'), level: 'intermediate' },
  { word: 'settings', arabic: 'إعدادات', example: 'Change the settings here.', category: 'technology', imageUrl: getImageUrl('settings gear'), level: 'intermediate' },
  { word: 'notification', arabic: 'إشعار', example: 'I got a new notification.', category: 'technology', imageUrl: getImageUrl('notification alert'), level: 'intermediate' },
  { word: 'account', arabic: 'حساب', example: 'Create a new account.', category: 'technology', imageUrl: getImageUrl('account login'), level: 'intermediate' },
  { word: 'profile', arabic: 'ملف شخصي', example: 'Update your profile picture.', category: 'technology', imageUrl: getImageUrl('profile user'), level: 'intermediate' },
  { word: 'streaming', arabic: 'بث مباشر', example: 'Watch movies via streaming.', category: 'technology', imageUrl: getImageUrl('streaming video'), level: 'intermediate' },
  { word: 'social media', arabic: 'وسائل التواصل', example: 'Social media is popular.', category: 'technology', imageUrl: getImageUrl('social media apps'), level: 'intermediate' },
  { word: 'privacy', arabic: 'خصوصية', example: 'Protect your privacy online.', category: 'technology', imageUrl: getImageUrl('privacy security'), level: 'intermediate' },
  { word: 'virus', arabic: 'فيروس', example: 'A virus infected the computer.', category: 'technology', imageUrl: getImageUrl('computer virus'), level: 'intermediate' },
  
  // Legal & Government
  { word: 'law', arabic: 'قانون', example: 'Everyone must follow the law.', category: 'legal', imageUrl: getImageUrl('law justice'), level: 'intermediate' },
  { word: 'court', arabic: 'محكمة', example: 'The case went to court.', category: 'legal', imageUrl: getImageUrl('court law'), level: 'intermediate' },
  { word: 'judge', arabic: 'قاضي', example: 'The judge made a decision.', category: 'legal', imageUrl: getImageUrl('judge court'), level: 'intermediate' },
  { word: 'witness', arabic: 'شاهد', example: 'The witness told the truth.', category: 'legal', imageUrl: getImageUrl('witness court'), level: 'intermediate' },
  { word: 'evidence', arabic: 'دليل', example: 'Show the evidence clearly.', category: 'legal', imageUrl: getImageUrl('evidence investigation'), level: 'intermediate' },
  { word: 'crime', arabic: 'جريمة', example: 'Crime rates are decreasing.', category: 'legal', imageUrl: getImageUrl('crime police'), level: 'intermediate' },
  { word: 'guilty', arabic: 'مذنب', example: 'He was found guilty.', category: 'legal', imageUrl: getImageUrl('guilty verdict'), level: 'intermediate' },
  { word: 'innocent', arabic: 'بريء', example: 'She was proven innocent.', category: 'legal', imageUrl: getImageUrl('innocent person'), level: 'intermediate' },
  { word: 'lawyer', arabic: 'محامي', example: 'Hire a good lawyer.', category: 'legal', imageUrl: getImageUrl('lawyer legal'), level: 'intermediate' },
  { word: 'trial', arabic: 'محاكمة', example: 'The trial begins tomorrow.', category: 'legal', imageUrl: getImageUrl('trial court'), level: 'intermediate' },
  { word: 'verdict', arabic: 'حكم', example: 'The verdict was fair.', category: 'legal', imageUrl: getImageUrl('verdict judgment'), level: 'intermediate' },
  { word: 'prison', arabic: 'سجن', example: 'He was sent to prison.', category: 'legal', imageUrl: getImageUrl('prison jail'), level: 'intermediate' },
  { word: 'government', arabic: 'حكومة', example: 'The government helps citizens.', category: 'legal', imageUrl: getImageUrl('government building'), level: 'intermediate' },
  { word: 'election', arabic: 'انتخابات', example: 'Elections are important.', category: 'legal', imageUrl: getImageUrl('election voting'), level: 'intermediate' },
  { word: 'citizen', arabic: 'مواطن', example: 'Every citizen has rights.', category: 'legal', imageUrl: getImageUrl('citizen people'), level: 'intermediate' },
  
  // Art & Music
  { word: 'painting', arabic: 'لوحة', example: 'This painting is beautiful.', category: 'arts', imageUrl: getImageUrl('painting art'), level: 'intermediate' },
  { word: 'sculpture', arabic: 'منحوتة', example: 'The sculpture is ancient.', category: 'arts', imageUrl: getImageUrl('sculpture art'), level: 'intermediate' },
  { word: 'gallery', arabic: 'معرض فني', example: 'Visit the art gallery.', category: 'arts', imageUrl: getImageUrl('gallery art'), level: 'intermediate' },
  { word: 'exhibition', arabic: 'معرض', example: 'The exhibition was amazing.', category: 'arts', imageUrl: getImageUrl('exhibition display'), level: 'intermediate' },
  { word: 'artist', arabic: 'فنان', example: 'She is a talented artist.', category: 'arts', imageUrl: getImageUrl('artist painting'), level: 'intermediate' },
  { word: 'musician', arabic: 'موسيقي', example: 'He is a famous musician.', category: 'arts', imageUrl: getImageUrl('musician music'), level: 'intermediate' },
  { word: 'composer', arabic: 'ملحن', example: 'The composer wrote beautiful music.', category: 'arts', imageUrl: getImageUrl('composer music'), level: 'intermediate' },
  { word: 'instrument', arabic: 'آلة موسيقية', example: 'Learn to play an instrument.', category: 'arts', imageUrl: getImageUrl('instrument music'), level: 'intermediate' },
  { word: 'piano', arabic: 'بيانو', example: 'She plays the piano well.', category: 'arts', imageUrl: getImageUrl('piano music'), level: 'intermediate' },
  { word: 'guitar', arabic: 'جيتار', example: 'He loves playing guitar.', category: 'arts', imageUrl: getImageUrl('guitar music'), level: 'intermediate' },
  { word: 'violin', arabic: 'كمان', example: 'The violin sounds beautiful.', category: 'arts', imageUrl: getImageUrl('violin music'), level: 'intermediate' },
  { word: 'drums', arabic: 'طبول', example: 'Drums give rhythm to music.', category: 'arts', imageUrl: getImageUrl('drums music'), level: 'intermediate' },
  { word: 'orchestra', arabic: 'أوركسترا', example: 'The orchestra performed live.', category: 'arts', imageUrl: getImageUrl('orchestra music'), level: 'intermediate' },
  { word: 'rhythm', arabic: 'إيقاع', example: 'Feel the rhythm of the music.', category: 'arts', imageUrl: getImageUrl('rhythm music'), level: 'intermediate' },
  { word: 'melody', arabic: 'لحن', example: 'The melody is catchy.', category: 'arts', imageUrl: getImageUrl('melody music'), level: 'intermediate' },
  
  // Housing & Real Estate
  { word: 'apartment', arabic: 'شقة', example: 'I live in an apartment.', category: 'housing', imageUrl: getImageUrl('apartment building'), level: 'intermediate' },
  { word: 'rent', arabic: 'إيجار', example: 'Pay the rent monthly.', category: 'housing', imageUrl: getImageUrl('rent payment'), level: 'intermediate' },
  { word: 'mortgage', arabic: 'رهن عقاري', example: 'Apply for a mortgage.', category: 'housing', imageUrl: getImageUrl('mortgage loan'), level: 'intermediate' },
  { word: 'landlord', arabic: 'مالك العقار', example: 'The landlord is friendly.', category: 'housing', imageUrl: getImageUrl('landlord property'), level: 'intermediate' },
  { word: 'tenant', arabic: 'مستأجر', example: 'The tenant pays on time.', category: 'housing', imageUrl: getImageUrl('tenant apartment'), level: 'intermediate' },
  { word: 'lease', arabic: 'عقد إيجار', example: 'Sign the lease agreement.', category: 'housing', imageUrl: getImageUrl('lease contract'), level: 'intermediate' },
  { word: 'deposit', arabic: 'عربون', example: 'Pay the security deposit.', category: 'housing', imageUrl: getImageUrl('deposit money'), level: 'intermediate' },
  { word: 'renovation', arabic: 'تجديد', example: 'The house needs renovation.', category: 'housing', imageUrl: getImageUrl('renovation construction'), level: 'intermediate' },
  { word: 'furniture', arabic: 'أثاث', example: 'Buy new furniture.', category: 'housing', imageUrl: getImageUrl('furniture home'), level: 'intermediate' },
  { word: 'neighborhood', arabic: 'حي', example: 'This is a nice neighborhood.', category: 'housing', imageUrl: getImageUrl('neighborhood street'), level: 'intermediate' },
  { word: 'location', arabic: 'موقع', example: 'Location is very important.', category: 'housing', imageUrl: getImageUrl('location map'), level: 'intermediate' },
  { word: 'property', arabic: 'ملكية', example: 'This is private property.', category: 'housing', imageUrl: getImageUrl('property house'), level: 'intermediate' },
  { word: 'balcony', arabic: 'شرفة', example: 'Enjoy the view from the balcony.', category: 'housing', imageUrl: getImageUrl('balcony view'), level: 'intermediate' },
  { word: 'basement', arabic: 'قبو', example: 'Store things in the basement.', category: 'housing', imageUrl: getImageUrl('basement storage'), level: 'intermediate' },
  { word: 'attic', arabic: 'علية', example: 'The attic is dusty.', category: 'housing', imageUrl: getImageUrl('attic room'), level: 'intermediate' },
]

export const ADDITIONAL_ADVANCED_WORDS: WordItem[] = [
  // ============ MORE ADVANCED WORDS ============
  
  // Medical & Healthcare Advanced
  { word: 'anesthesia', arabic: 'تخدير', example: 'The patient received anesthesia.', category: 'medical', imageUrl: getImageUrl('anesthesia surgery'), level: 'advanced' },
  { word: 'antibiotics', arabic: 'مضادات حيوية', example: 'The doctor prescribed antibiotics.', category: 'medical', imageUrl: getImageUrl('antibiotics medicine'), level: 'advanced' },
  { word: 'biopsy', arabic: 'خزعة', example: 'A biopsy was performed.', category: 'medical', imageUrl: getImageUrl('biopsy medical'), level: 'advanced' },
  { word: 'chronic', arabic: 'مزمن', example: 'He has a chronic illness.', category: 'medical', imageUrl: getImageUrl('chronic illness'), level: 'advanced' },
  { word: 'contagious', arabic: 'معدي', example: 'This disease is contagious.', category: 'medical', imageUrl: getImageUrl('contagious disease'), level: 'advanced' },
  { word: 'diagnosis', arabic: 'تشخيص', example: 'Wait for the diagnosis.', category: 'medical', imageUrl: getImageUrl('diagnosis medical'), level: 'advanced' },
  { word: 'epidemic', arabic: 'وباء', example: 'The epidemic spread quickly.', category: 'medical', imageUrl: getImageUrl('epidemic disease'), level: 'advanced' },
  { word: 'fatigue', arabic: 'إرهاق', example: 'Fatigue is a common symptom.', category: 'medical', imageUrl: getImageUrl('fatigue tired'), level: 'advanced' },
  { word: 'inflammation', arabic: 'التهاب', example: 'Reduce the inflammation.', category: 'medical', imageUrl: getImageUrl('inflammation medical'), level: 'advanced' },
  { word: 'metabolism', arabic: 'أيض', example: 'Exercise boosts metabolism.', category: 'medical', imageUrl: getImageUrl('metabolism body'), level: 'advanced' },
  { word: 'prognosis', arabic: 'توقعات طبية', example: 'The prognosis is positive.', category: 'medical', imageUrl: getImageUrl('prognosis medical'), level: 'advanced' },
  { word: 'rehabilitation', arabic: 'تأهيل', example: 'Rehabilitation takes time.', category: 'medical', imageUrl: getImageUrl('rehabilitation therapy'), level: 'advanced' },
  { word: 'therapeutic', arabic: 'علاجي', example: 'Music has therapeutic effects.', category: 'medical', imageUrl: getImageUrl('therapeutic healing'), level: 'advanced' },
  { word: 'transplant', arabic: 'زراعة أعضاء', example: 'He needs a heart transplant.', category: 'medical', imageUrl: getImageUrl('transplant surgery'), level: 'advanced' },
  { word: 'trauma', arabic: 'صدمة', example: 'The trauma affected him deeply.', category: 'medical', imageUrl: getImageUrl('trauma recovery'), level: 'advanced' },
  
  // Business & Finance Advanced
  { word: 'bankruptcy', arabic: 'إفلاس', example: 'The company declared bankruptcy.', category: 'business', imageUrl: getImageUrl('bankruptcy finance'), level: 'advanced' },
  { word: 'collateral', arabic: 'ضمانات', example: 'Provide collateral for the loan.', category: 'business', imageUrl: getImageUrl('collateral loan'), level: 'advanced' },
  { word: 'consortium', arabic: 'تجمع شركات', example: 'The consortium won the bid.', category: 'business', imageUrl: getImageUrl('consortium business'), level: 'advanced' },
  { word: 'derivative', arabic: 'مشتقة مالية', example: 'Trade in financial derivatives.', category: 'business', imageUrl: getImageUrl('derivative finance'), level: 'advanced' },
  { word: 'divestment', arabic: 'تصفية استثمار', example: 'The divestment was strategic.', category: 'business', imageUrl: getImageUrl('divestment finance'), level: 'advanced' },
  { word: 'entrepreneurship', arabic: 'ريادة أعمال', example: 'Entrepreneurship requires risk-taking.', category: 'business', imageUrl: getImageUrl('entrepreneurship startup'), level: 'advanced' },
  { word: 'fiduciary', arabic: 'ائتماني', example: 'Maintain fiduciary responsibility.', category: 'business', imageUrl: getImageUrl('fiduciary trust'), level: 'advanced' },
  { word: 'franchise', arabic: 'امتياز تجاري', example: 'Open a franchise business.', category: 'business', imageUrl: getImageUrl('franchise business'), level: 'advanced' },
  { word: 'liquidation', arabic: 'تصفية', example: 'The company went into liquidation.', category: 'business', imageUrl: getImageUrl('liquidation sale'), level: 'advanced' },
  { word: 'procurement', arabic: 'شراء / توريد', example: 'Handle the procurement process.', category: 'business', imageUrl: getImageUrl('procurement supply'), level: 'advanced' },
  { word: 'stakeholder', arabic: 'صاحب مصلحة', example: 'Inform all stakeholders.', category: 'business', imageUrl: getImageUrl('stakeholder meeting'), level: 'advanced' },
  { word: 'subsidiary', arabic: 'شركة تابعة', example: 'Manage the subsidiary company.', category: 'business', imageUrl: getImageUrl('subsidiary business'), level: 'advanced' },
  { word: 'valuation', arabic: 'تقييم', example: 'The company valuation increased.', category: 'business', imageUrl: getImageUrl('valuation finance'), level: 'advanced' },
  { word: 'venture', arabic: 'مشروع استثماري', example: 'Invest in a new venture.', category: 'business', imageUrl: getImageUrl('venture capital'), level: 'advanced' },
  { word: 'whistleblower', arabic: 'مُبلغ عن فساد', example: 'The whistleblower exposed fraud.', category: 'business', imageUrl: getImageUrl('whistleblower report'), level: 'advanced' },
  
  // Legal Advanced
  { word: 'affidavit', arabic: 'إفادة مكتوبة', example: 'Sign the affidavit.', category: 'legal', imageUrl: getImageUrl('affidavit document'), level: 'advanced' },
  { word: 'arbitration', arabic: 'تحكيم', example: 'Resolve disputes through arbitration.', category: 'legal', imageUrl: getImageUrl('arbitration legal'), level: 'advanced' },
  { word: 'clemency', arabic: 'رأفة', example: 'Request for clemency was denied.', category: 'legal', imageUrl: getImageUrl('clemency mercy'), level: 'advanced' },
  { word: 'defamation', arabic: 'تشهير', example: 'Sue for defamation of character.', category: 'legal', imageUrl: getImageUrl('defamation slander'), level: 'advanced' },
  { word: 'extradition', arabic: 'تسليم المجرمين', example: 'Request extradition from abroad.', category: 'legal', imageUrl: getImageUrl('extradition legal'), level: 'advanced' },
  { word: 'indictment', arabic: 'لائحة اتهام', example: 'The indictment was filed.', category: 'legal', imageUrl: getImageUrl('indictment court'), level: 'advanced' },
  { word: 'injunction', arabic: 'أمر قضائي', example: 'The court issued an injunction.', category: 'legal', imageUrl: getImageUrl('injunction legal'), level: 'advanced' },
  { word: 'litigation', arabic: 'تقاضي', example: 'Avoid lengthy litigation.', category: 'legal', imageUrl: getImageUrl('litigation court'), level: 'advanced' },
  { word: 'malpractice', arabic: 'إهمال مهني', example: 'Sue for medical malpractice.', category: 'legal', imageUrl: getImageUrl('malpractice legal'), level: 'advanced' },
  { word: 'negligence', arabic: 'إهمال', example: 'Claim damages for negligence.', category: 'legal', imageUrl: getImageUrl('negligence liability'), level: 'advanced' },
  { word: 'patent', arabic: 'براءة اختراع', example: 'File a patent application.', category: 'legal', imageUrl: getImageUrl('patent invention'), level: 'advanced' },
  { word: 'perjury', arabic: 'شهادة زور', example: 'Perjury is a serious crime.', category: 'legal', imageUrl: getImageUrl('perjury court'), level: 'advanced' },
  { word: 'plaintiff', arabic: 'المدعي', example: 'The plaintiff filed the case.', category: 'legal', imageUrl: getImageUrl('plaintiff court'), level: 'advanced' },
  { word: 'subpoena', arabic: 'استدعاء للمحكمة', example: 'Receive a subpoena to testify.', category: 'legal', imageUrl: getImageUrl('subpoena court'), level: 'advanced' },
  { word: 'tort', arabic: 'ضرر مدني', example: 'Study tort law carefully.', category: 'legal', imageUrl: getImageUrl('tort law'), level: 'advanced' },
  
  // Technology Advanced
  { word: 'bandwidth', arabic: 'عرض النطاق', example: 'Increase the bandwidth.', category: 'technology', imageUrl: getImageUrl('bandwidth network'), level: 'advanced' },
  { word: 'blockchain', arabic: 'سلسلة الكتل', example: 'Blockchain ensures transparency.', category: 'technology', imageUrl: getImageUrl('blockchain crypto'), level: 'advanced' },
  { word: 'cryptocurrency', arabic: 'عملة رقمية', example: 'Invest in cryptocurrency.', category: 'technology', imageUrl: getImageUrl('cryptocurrency bitcoin'), level: 'advanced' },
  { word: 'decryption', arabic: 'فك التشفير', example: 'Decryption requires a key.', category: 'technology', imageUrl: getImageUrl('decryption security'), level: 'advanced' },
  { word: 'encryption', arabic: 'تشفير', example: 'Use encryption for security.', category: 'technology', imageUrl: getImageUrl('encryption security'), level: 'advanced' },
  { word: 'firewall', arabic: 'جدار حماية', example: 'Install a firewall.', category: 'technology', imageUrl: getImageUrl('firewall security'), level: 'advanced' },
  { word: 'infrastructure', arabic: 'بنية تحتية', example: 'Upgrade IT infrastructure.', category: 'technology', imageUrl: getImageUrl('infrastructure network'), level: 'advanced' },
  { word: 'interoperability', arabic: 'قابلية التشغيل البيني', example: 'Ensure system interoperability.', category: 'technology', imageUrl: getImageUrl('interoperability systems'), level: 'advanced' },
  { word: 'latency', arabic: 'زمن الوصول', example: 'Reduce network latency.', category: 'technology', imageUrl: getImageUrl('latency network'), level: 'advanced' },
  { word: 'malware', arabic: 'برمجيات ضارة', example: 'Protect against malware.', category: 'technology', imageUrl: getImageUrl('malware virus'), level: 'advanced' },
  { word: 'scalability', arabic: 'قابلية التوسع', example: 'Consider scalability in design.', category: 'technology', imageUrl: getImageUrl('scalability growth'), level: 'advanced' },
  { word: 'virtualization', arabic: 'المحاكاة الافتراضية', example: 'Implement server virtualization.', category: 'technology', imageUrl: getImageUrl('virtualization cloud'), level: 'advanced' },
  { word: 'protocol', arabic: 'بروتوكول', example: 'Follow the network protocol.', category: 'technology', imageUrl: getImageUrl('protocol network'), level: 'advanced' },
  { word: 'redundancy', arabic: 'تكرار / احتياطي', example: 'Build in redundancy.', category: 'technology', imageUrl: getImageUrl('redundancy backup'), level: 'advanced' },
  { word: 'repository', arabic: 'مستودع', example: 'Push code to the repository.', category: 'technology', imageUrl: getImageUrl('repository code'), level: 'advanced' },
  
  // Environmental Science Advanced
  { word: 'anthropogenic', arabic: 'بشري المنشأ', example: 'Anthropogenic climate change is real.', category: 'environment', imageUrl: getImageUrl('anthropogenic climate'), level: 'advanced' },
  { word: 'biodegradable', arabic: 'قابل للتحلل', example: 'Use biodegradable products.', category: 'environment', imageUrl: getImageUrl('biodegradable eco'), level: 'advanced' },
  { word: 'biosphere', arabic: 'غلاف حيوي', example: 'Protect our biosphere.', category: 'environment', imageUrl: getImageUrl('biosphere earth'), level: 'advanced' },
  { word: 'contamination', arabic: 'تلوث', example: 'Avoid water contamination.', category: 'environment', imageUrl: getImageUrl('contamination pollution'), level: 'advanced' },
  { word: 'desertification', arabic: 'تصحر', example: 'Desertification is a threat.', category: 'environment', imageUrl: getImageUrl('desertification desert'), level: 'advanced' },
  { word: 'emission', arabic: 'انبعاثات', example: 'Reduce carbon emissions.', category: 'environment', imageUrl: getImageUrl('emission pollution'), level: 'advanced' },
  { word: 'endangered', arabic: 'مهدد بالانقراض', example: 'Protect endangered species.', category: 'environment', imageUrl: getImageUrl('endangered species'), level: 'advanced' },
  { word: 'erosion', arabic: 'تآكل', example: 'Soil erosion is problematic.', category: 'environment', imageUrl: getImageUrl('erosion soil'), level: 'advanced' },
  { word: 'fossil fuel', arabic: 'وقود أحفوري', example: 'Reduce fossil fuel use.', category: 'environment', imageUrl: getImageUrl('fossil fuel oil'), level: 'advanced' },
  { word: 'greenhouse', arabic: 'دفيئة', example: 'Greenhouse gases trap heat.', category: 'environment', imageUrl: getImageUrl('greenhouse effect'), level: 'advanced' },
  { word: 'ozone', arabic: 'أوزون', example: 'The ozone layer protects us.', category: 'environment', imageUrl: getImageUrl('ozone layer'), level: 'advanced' },
  { word: 'pesticide', arabic: 'مبيد حشري', example: 'Avoid harmful pesticides.', category: 'environment', imageUrl: getImageUrl('pesticide farming'), level: 'advanced' },
  { word: 'photosynthesis', arabic: 'التمثيل الضوئي', example: 'Plants use photosynthesis.', category: 'environment', imageUrl: getImageUrl('photosynthesis plant'), level: 'advanced' },
  { word: 'reforestation', arabic: 'إعادة التشجير', example: 'Support reforestation efforts.', category: 'environment', imageUrl: getImageUrl('reforestation trees'), level: 'advanced' },
  { word: 'watershed', arabic: 'مستجمع مائي', example: 'Protect the watershed area.', category: 'environment', imageUrl: getImageUrl('watershed river'), level: 'advanced' },
  
  // Psychology Advanced
  { word: 'anxiety', arabic: 'قلق', example: 'Manage anxiety effectively.', category: 'psychology', imageUrl: getImageUrl('anxiety stress'), level: 'advanced' },
  { word: 'behavioral', arabic: 'سلوكي', example: 'Study behavioral patterns.', category: 'psychology', imageUrl: getImageUrl('behavioral psychology'), level: 'advanced' },
  { word: 'cognitive', arabic: 'إدراكي', example: 'Cognitive abilities vary.', category: 'psychology', imageUrl: getImageUrl('cognitive brain'), level: 'advanced' },
  { word: 'conditioning', arabic: 'تكييف', example: 'Classical conditioning experiments.', category: 'psychology', imageUrl: getImageUrl('conditioning psychology'), level: 'advanced' },
  { word: 'depression', arabic: 'اكتئاب', example: 'Seek help for depression.', category: 'psychology', imageUrl: getImageUrl('depression sadness'), level: 'advanced' },
  { word: 'developmental', arabic: 'تنموي', example: 'Study developmental stages.', category: 'psychology', imageUrl: getImageUrl('developmental growth'), level: 'advanced' },
  { word: 'hallucination', arabic: 'هلوسة', example: 'Hallucinations are symptoms.', category: 'psychology', imageUrl: getImageUrl('hallucination mind'), level: 'advanced' },
  { word: 'neurological', arabic: 'عصبي', example: 'Neurological disorders are complex.', category: 'psychology', imageUrl: getImageUrl('neurological brain'), level: 'advanced' },
  { word: 'phobia', arabic: 'رهاب', example: 'Treat phobias with therapy.', category: 'psychology', imageUrl: getImageUrl('phobia fear'), level: 'advanced' },
  { word: 'psychotherapy', arabic: 'علاج نفسي', example: 'Psychotherapy helps many.', category: 'psychology', imageUrl: getImageUrl('psychotherapy counseling'), level: 'advanced' },
  { word: 'schizophrenia', arabic: 'انفصام الشخصية', example: 'Schizophrenia requires treatment.', category: 'psychology', imageUrl: getImageUrl('schizophrenia mental'), level: 'advanced' },
  { word: 'stimulus', arabic: 'منبه', example: 'Response to a stimulus.', category: 'psychology', imageUrl: getImageUrl('stimulus response'), level: 'advanced' },
  { word: 'subconscious', arabic: 'العقل الباطن', example: 'The subconscious affects behavior.', category: 'psychology', imageUrl: getImageUrl('subconscious mind'), level: 'advanced' },
  { word: 'temperament', arabic: 'مزاج', example: 'Temperament differs among people.', category: 'psychology', imageUrl: getImageUrl('temperament personality'), level: 'advanced' },
  { word: 'therapy', arabic: 'علاج', example: 'Therapy can be helpful.', category: 'psychology', imageUrl: getImageUrl('therapy counseling'), level: 'advanced' },
  
  // Academic & Research
  { word: 'abstract', arabic: 'ملخص', example: 'Write an abstract first.', category: 'academic', imageUrl: getImageUrl('abstract paper'), level: 'advanced' },
  { word: 'bibliography', arabic: 'قائمة المراجع', example: 'Include a bibliography.', category: 'academic', imageUrl: getImageUrl('bibliography books'), level: 'advanced' },
  { word: 'citation', arabic: 'اقتباس', example: 'Use proper citation format.', category: 'academic', imageUrl: getImageUrl('citation reference'), level: 'advanced' },
  { word: 'dissertation', arabic: 'رسالة دكتوراه', example: 'Complete your dissertation.', category: 'academic', imageUrl: getImageUrl('dissertation thesis'), level: 'advanced' },
  { word: 'empirical', arabic: 'تجريبي', example: 'Gather empirical evidence.', category: 'academic', imageUrl: getImageUrl('empirical research'), level: 'advanced' },
  { word: 'hypothesis', arabic: 'فرضية', example: 'Test your hypothesis.', category: 'academic', imageUrl: getImageUrl('hypothesis science'), level: 'advanced' },
  { word: 'interdisciplinary', arabic: 'متعدد التخصصات', example: 'Interdisciplinary research is growing.', category: 'academic', imageUrl: getImageUrl('interdisciplinary study'), level: 'advanced' },
  { word: 'literature review', arabic: 'مراجعة الأدبيات', example: 'Conduct a literature review.', category: 'academic', imageUrl: getImageUrl('literature review'), level: 'advanced' },
  { word: 'methodology', arabic: 'منهجية', example: 'Explain your methodology.', category: 'academic', imageUrl: getImageUrl('methodology research'), level: 'advanced' },
  { word: 'paradigm', arabic: 'نموذج', example: 'A new paradigm emerged.', category: 'academic', imageUrl: getImageUrl('paradigm shift'), level: 'advanced' },
  { word: 'peer review', arabic: 'مراجعة الأقران', example: 'Submit for peer review.', category: 'academic', imageUrl: getImageUrl('peer review'), level: 'advanced' },
  { word: 'plagiarism', arabic: 'انتحال', example: 'Avoid plagiarism always.', category: 'academic', imageUrl: getImageUrl('plagiarism academic'), level: 'advanced' },
  { word: 'qualitative', arabic: 'نوعي', example: 'Use qualitative methods.', category: 'academic', imageUrl: getImageUrl('qualitative research'), level: 'advanced' },
  { word: 'quantitative', arabic: 'كمي', example: 'Conduct quantitative analysis.', category: 'academic', imageUrl: getImageUrl('quantitative data'), level: 'advanced' },
  { word: 'symposium', arabic: 'ندوة', example: 'Present at the symposium.', category: 'academic', imageUrl: getImageUrl('symposium conference'), level: 'advanced' },
  
  // International Relations
  { word: 'alliance', arabic: 'تحالف', example: 'Form a strategic alliance.', category: 'politics', imageUrl: getImageUrl('alliance partnership'), level: 'advanced' },
  { word: 'bilateral', arabic: 'ثنائي', example: 'Sign a bilateral agreement.', category: 'politics', imageUrl: getImageUrl('bilateral agreement'), level: 'advanced' },
  { word: 'coalition', arabic: 'ائتلاف', example: 'Form a coalition government.', category: 'politics', imageUrl: getImageUrl('coalition politics'), level: 'advanced' },
  { word: 'embargo', arabic: 'حظر', example: 'Impose an economic embargo.', category: 'politics', imageUrl: getImageUrl('embargo trade'), level: 'advanced' },
  { word: 'geopolitical', arabic: 'جيوسياسي', example: 'Analyze geopolitical factors.', category: 'politics', imageUrl: getImageUrl('geopolitical map'), level: 'advanced' },
  { word: 'humanitarian', arabic: 'إنساني', example: 'Provide humanitarian aid.', category: 'politics', imageUrl: getImageUrl('humanitarian aid'), level: 'advanced' },
  { word: 'multilateral', arabic: 'متعدد الأطراف', example: 'Multilateral negotiations continue.', category: 'politics', imageUrl: getImageUrl('multilateral meeting'), level: 'advanced' },
  { word: 'neutrality', arabic: 'حياد', example: 'Maintain political neutrality.', category: 'politics', imageUrl: getImageUrl('neutrality peace'), level: 'advanced' },
  { word: 'proliferation', arabic: 'انتشار', example: 'Prevent nuclear proliferation.', category: 'politics', imageUrl: getImageUrl('proliferation nuclear'), level: 'advanced' },
  { word: 'ratification', arabic: 'تصديق', example: 'The treaty awaits ratification.', category: 'politics', imageUrl: getImageUrl('ratification treaty'), level: 'advanced' },
  { word: 'reconciliation', arabic: 'مصالحة', example: 'Work toward reconciliation.', category: 'politics', imageUrl: getImageUrl('reconciliation peace'), level: 'advanced' },
  { word: 'refugee', arabic: 'لاجئ', example: 'Help refugees in need.', category: 'politics', imageUrl: getImageUrl('refugee crisis'), level: 'advanced' },
  { word: 'sovereignty', arabic: 'سيادة', example: 'Respect national sovereignty.', category: 'politics', imageUrl: getImageUrl('sovereignty nation'), level: 'advanced' },
  { word: 'tariff', arabic: 'تعريفة جمركية', example: 'Impose tariffs on imports.', category: 'politics', imageUrl: getImageUrl('tariff trade'), level: 'advanced' },
  { word: 'veto', arabic: 'حق النقض', example: 'Use the veto power.', category: 'politics', imageUrl: getImageUrl('veto power'), level: 'advanced' },
  
  // Architecture & Engineering
  { word: 'aerodynamic', arabic: 'ديناميكي هوائي', example: 'Aerodynamic design reduces drag.', category: 'engineering', imageUrl: getImageUrl('aerodynamic design'), level: 'advanced' },
  { word: 'blueprint', arabic: 'مخطط', example: 'Review the blueprint.', category: 'engineering', imageUrl: getImageUrl('blueprint architecture'), level: 'advanced' },
  { word: 'calibration', arabic: 'معايرة', example: 'Calibration ensures accuracy.', category: 'engineering', imageUrl: getImageUrl('calibration measurement'), level: 'advanced' },
  { word: 'composite', arabic: 'مركب', example: 'Use composite materials.', category: 'engineering', imageUrl: getImageUrl('composite material'), level: 'advanced' },
  { word: 'corrosion', arabic: 'تآكل', example: 'Prevent metal corrosion.', category: 'engineering', imageUrl: getImageUrl('corrosion rust'), level: 'advanced' },
  { word: 'durability', arabic: 'متانة', example: 'Test for durability.', category: 'engineering', imageUrl: getImageUrl('durability strength'), level: 'advanced' },
  { word: 'fabrication', arabic: 'تصنيع', example: 'Fabrication requires precision.', category: 'engineering', imageUrl: getImageUrl('fabrication manufacturing'), level: 'advanced' },
  { word: 'hydraulic', arabic: 'هيدروليكي', example: 'Hydraulic systems are powerful.', category: 'engineering', imageUrl: getImageUrl('hydraulic system'), level: 'advanced' },
  { word: 'insulation', arabic: 'عزل', example: 'Good insulation saves energy.', category: 'engineering', imageUrl: getImageUrl('insulation building'), level: 'advanced' },
  { word: 'load-bearing', arabic: 'حامل للحمولة', example: 'Load-bearing walls are important.', category: 'engineering', imageUrl: getImageUrl('load-bearing wall'), level: 'advanced' },
  { word: 'maintenance', arabic: 'صيانة', example: 'Regular maintenance is crucial.', category: 'engineering', imageUrl: getImageUrl('maintenance repair'), level: 'advanced' },
  { word: 'prototype', arabic: 'نموذج أولي', example: 'Build a prototype first.', category: 'engineering', imageUrl: getImageUrl('prototype design'), level: 'advanced' },
  { word: 'reinforcement', arabic: 'تعزيز', example: 'Add reinforcement to concrete.', category: 'engineering', imageUrl: getImageUrl('reinforcement steel'), level: 'advanced' },
  { word: 'structural', arabic: 'إنشائي', example: 'Check structural integrity.', category: 'engineering', imageUrl: getImageUrl('structural engineering'), level: 'advanced' },
  { word: 'turbine', arabic: 'توربين', example: 'Wind turbines generate electricity.', category: 'engineering', imageUrl: getImageUrl('turbine wind'), level: 'advanced' },
  
  // Linguistics & Language
  { word: 'bilingual', arabic: 'ثنائي اللغة', example: 'She is bilingual.', category: 'language', imageUrl: getImageUrl('bilingual speaker'), level: 'advanced' },
  { word: 'colloquial', arabic: 'عامي', example: 'Use colloquial expressions.', category: 'language', imageUrl: getImageUrl('colloquial speech'), level: 'advanced' },
  { word: 'dialect', arabic: 'لهجة', example: 'Each region has a dialect.', category: 'language', imageUrl: getImageUrl('dialect speech'), level: 'advanced' },
  { word: 'etymology', arabic: 'أصل الكلمة', example: 'Study word etymology.', category: 'language', imageUrl: getImageUrl('etymology words'), level: 'advanced' },
  { word: 'fluency', arabic: 'طلاقة', example: 'Achieve fluency in speaking.', category: 'language', imageUrl: getImageUrl('fluency speaking'), level: 'advanced' },
  { word: 'grammar', arabic: 'قواعد', example: 'Learn English grammar.', category: 'language', imageUrl: getImageUrl('grammar rules'), level: 'advanced' },
  { word: 'idiomatic', arabic: 'اصطلاحي', example: 'Use idiomatic expressions.', category: 'language', imageUrl: getImageUrl('idiomatic phrase'), level: 'advanced' },
  { word: 'intonation', arabic: 'تنغيم', example: 'Work on your intonation.', category: 'language', imageUrl: getImageUrl('intonation speech'), level: 'advanced' },
  { word: 'linguistics', arabic: 'علم اللغة', example: 'Study linguistics formally.', category: 'language', imageUrl: getImageUrl('linguistics study'), level: 'advanced' },
  { word: 'morphology', arabic: 'علم الصرف', example: 'Morphology studies word forms.', category: 'language', imageUrl: getImageUrl('morphology language'), level: 'advanced' },
  { word: 'phonetics', arabic: 'علم الأصوات', example: 'Phonetics helps pronunciation.', category: 'language', imageUrl: getImageUrl('phonetics speech'), level: 'advanced' },
  { word: 'pragmatics', arabic: 'التداولية', example: 'Pragmatics studies context.', category: 'language', imageUrl: getImageUrl('pragmatics language'), level: 'advanced' },
  { word: 'semantics', arabic: 'علم الدلالة', example: 'Semantics explores meaning.', category: 'language', imageUrl: getImageUrl('semantics meaning'), level: 'advanced' },
  { word: 'syntax', arabic: 'بناء الجملة', example: 'Study English syntax.', category: 'language', imageUrl: getImageUrl('syntax grammar'), level: 'advanced' },
  { word: 'vernacular', arabic: 'العامية', example: 'Write in the vernacular.', category: 'language', imageUrl: getImageUrl('vernacular speech'), level: 'advanced' },
]
