import { ADDITIONAL_BEGINNER_WORDS, ADDITIONAL_INTERMEDIATE_WORDS, ADDITIONAL_ADVANCED_WORDS } from './additional-words'

export interface WordItem {
  word: string
  arabic: string
  example: string
  category: string
  imageUrl: string
  level: 'beginner' | 'intermediate' | 'advanced'
}

const getImageUrl = (keyword: string) => `https://picsum.photos/seed/${encodeURIComponent(keyword.replace(/\s+/g, '-'))}/400/300`

const BASE_WORDS: WordItem[] = [
  // ============ BEGINNER LEVEL ============
  // Greetings & Basic Expressions
  { word: 'hello', arabic: 'مرحبا', example: 'Hello, how are you today?', category: 'greetings', imageUrl: getImageUrl('hello wave'), level: 'beginner' },
  { word: 'goodbye', arabic: 'وداعا', example: 'Goodbye, see you tomorrow!', category: 'greetings', imageUrl: getImageUrl('goodbye wave'), level: 'beginner' },
  { word: 'please', arabic: 'من فضلك', example: 'Please help me with this.', category: 'greetings', imageUrl: getImageUrl('polite request'), level: 'beginner' },
  { word: 'thank you', arabic: 'شكرا لك', example: 'Thank you for your kindness.', category: 'greetings', imageUrl: getImageUrl('thank you gratitude'), level: 'beginner' },
  { word: 'welcome', arabic: 'أهلا وسهلا', example: 'Welcome to our home!', category: 'greetings', imageUrl: getImageUrl('welcome home'), level: 'beginner' },
  { word: 'sorry', arabic: 'آسف', example: 'I am sorry for being late.', category: 'greetings', imageUrl: getImageUrl('apology'), level: 'beginner' },
  { word: 'excuse me', arabic: 'عذرا', example: 'Excuse me, can you help?', category: 'greetings', imageUrl: getImageUrl('polite'), level: 'beginner' },
  { word: 'yes', arabic: 'نعم', example: 'Yes, I agree with you.', category: 'greetings', imageUrl: getImageUrl('yes approval'), level: 'beginner' },
  { word: 'no', arabic: 'لا', example: 'No, I do not want it.', category: 'greetings', imageUrl: getImageUrl('no rejection'), level: 'beginner' },
  { word: 'maybe', arabic: 'ربما', example: 'Maybe we can go tomorrow.', category: 'greetings', imageUrl: getImageUrl('thinking maybe'), level: 'beginner' },

  // Family
  { word: 'family', arabic: 'عائلة', example: 'My family is very loving.', category: 'family', imageUrl: getImageUrl('happy family'), level: 'beginner' },
  { word: 'mother', arabic: 'أم', example: 'My mother cooks delicious food.', category: 'family', imageUrl: getImageUrl('mother love'), level: 'beginner' },
  { word: 'father', arabic: 'أب', example: 'My father works very hard.', category: 'family', imageUrl: getImageUrl('father family'), level: 'beginner' },
  { word: 'brother', arabic: 'أخ', example: 'My brother plays football.', category: 'family', imageUrl: getImageUrl('brother sibling'), level: 'beginner' },
  { word: 'sister', arabic: 'أخت', example: 'My sister loves reading books.', category: 'family', imageUrl: getImageUrl('sister sibling'), level: 'beginner' },
  { word: 'son', arabic: 'ابن', example: 'Their son is very smart.', category: 'family', imageUrl: getImageUrl('son child boy'), level: 'beginner' },
  { word: 'daughter', arabic: 'ابنة', example: 'Their daughter plays piano.', category: 'family', imageUrl: getImageUrl('daughter child girl'), level: 'beginner' },
  { word: 'grandfather', arabic: 'جد', example: 'My grandfather tells stories.', category: 'family', imageUrl: getImageUrl('grandfather elderly'), level: 'beginner' },
  { word: 'grandmother', arabic: 'جدة', example: 'My grandmother bakes cookies.', category: 'family', imageUrl: getImageUrl('grandmother elderly'), level: 'beginner' },
  { word: 'baby', arabic: 'طفل رضيع', example: 'The baby is sleeping peacefully.', category: 'family', imageUrl: getImageUrl('baby infant'), level: 'beginner' },
  { word: 'husband', arabic: 'زوج', example: 'Her husband is a doctor.', category: 'family', imageUrl: getImageUrl('husband man'), level: 'beginner' },
  { word: 'wife', arabic: 'زوجة', example: 'His wife is a teacher.', category: 'family', imageUrl: getImageUrl('wife woman'), level: 'beginner' },
  { word: 'uncle', arabic: 'عم / خال', example: 'My uncle lives in London.', category: 'family', imageUrl: getImageUrl('uncle family'), level: 'beginner' },
  { word: 'aunt', arabic: 'عمة / خالة', example: 'My aunt visits us often.', category: 'family', imageUrl: getImageUrl('aunt family'), level: 'beginner' },
  { word: 'cousin', arabic: 'ابن عم / ابن خال', example: 'My cousin is my best friend.', category: 'family', imageUrl: getImageUrl('cousin family'), level: 'beginner' },

  // Food & Drinks
  { word: 'water', arabic: 'ماء', example: 'I drink water every day.', category: 'food', imageUrl: getImageUrl('water glass'), level: 'beginner' },
  { word: 'food', arabic: 'طعام', example: 'The food is delicious.', category: 'food', imageUrl: getImageUrl('food meal'), level: 'beginner' },
  { word: 'bread', arabic: 'خبز', example: 'I eat bread for breakfast.', category: 'food', imageUrl: getImageUrl('bread bakery'), level: 'beginner' },
  { word: 'rice', arabic: 'أرز', example: 'Rice is my favorite food.', category: 'food', imageUrl: getImageUrl('rice bowl'), level: 'beginner' },
  { word: 'meat', arabic: 'لحم', example: 'We cook meat for dinner.', category: 'food', imageUrl: getImageUrl('meat steak'), level: 'beginner' },
  { word: 'chicken', arabic: 'دجاج', example: 'The chicken is very tasty.', category: 'food', imageUrl: getImageUrl('chicken food'), level: 'beginner' },
  { word: 'fish', arabic: 'سمك', example: 'Fish is healthy to eat.', category: 'food', imageUrl: getImageUrl('fish seafood'), level: 'beginner' },
  { word: 'egg', arabic: 'بيض', example: 'I eat eggs in the morning.', category: 'food', imageUrl: getImageUrl('eggs breakfast'), level: 'beginner' },
  { word: 'milk', arabic: 'حليب', example: 'Milk is good for health.', category: 'food', imageUrl: getImageUrl('milk dairy'), level: 'beginner' },
  { word: 'cheese', arabic: 'جبن', example: 'I love cheese on my pizza.', category: 'food', imageUrl: getImageUrl('cheese dairy'), level: 'beginner' },
  { word: 'apple', arabic: 'تفاحة', example: 'An apple a day is healthy.', category: 'food', imageUrl: getImageUrl('apple fruit'), level: 'beginner' },
  { word: 'banana', arabic: 'موز', example: 'Bananas are yellow and sweet.', category: 'food', imageUrl: getImageUrl('banana fruit'), level: 'beginner' },
  { word: 'orange', arabic: 'برتقال', example: 'I drink orange juice daily.', category: 'food', imageUrl: getImageUrl('orange fruit'), level: 'beginner' },
  { word: 'coffee', arabic: 'قهوة', example: 'I start my day with coffee.', category: 'food', imageUrl: getImageUrl('coffee cup'), level: 'beginner' },
  { word: 'tea', arabic: 'شاي', example: 'She prefers tea over coffee.', category: 'food', imageUrl: getImageUrl('tea cup'), level: 'beginner' },
  { word: 'juice', arabic: 'عصير', example: 'Fresh juice is healthy.', category: 'food', imageUrl: getImageUrl('juice fresh'), level: 'beginner' },
  { word: 'cake', arabic: 'كعكة', example: 'The birthday cake was delicious.', category: 'food', imageUrl: getImageUrl('cake dessert'), level: 'beginner' },
  { word: 'chocolate', arabic: 'شوكولاتة', example: 'Children love chocolate.', category: 'food', imageUrl: getImageUrl('chocolate sweet'), level: 'beginner' },
  { word: 'pizza', arabic: 'بيتزا', example: 'Pizza is my favorite food.', category: 'food', imageUrl: getImageUrl('pizza food'), level: 'beginner' },
  { word: 'burger', arabic: 'برجر', example: 'I want a cheese burger.', category: 'food', imageUrl: getImageUrl('burger food'), level: 'beginner' },

  // Animals
  { word: 'cat', arabic: 'قطة', example: 'The cat is sleeping on the sofa.', category: 'animals', imageUrl: getImageUrl('cat pet'), level: 'beginner' },
  { word: 'dog', arabic: 'كلب', example: 'The dog is very friendly.', category: 'animals', imageUrl: getImageUrl('dog pet'), level: 'beginner' },
  { word: 'bird', arabic: 'طائر', example: 'The bird sings beautifully.', category: 'animals', imageUrl: getImageUrl('bird flying'), level: 'beginner' },
  { word: 'fish', arabic: 'سمكة', example: 'Fish swim in the water.', category: 'animals', imageUrl: getImageUrl('fish aquarium'), level: 'beginner' },
  { word: 'horse', arabic: 'حصان', example: 'The horse runs very fast.', category: 'animals', imageUrl: getImageUrl('horse running'), level: 'beginner' },
  { word: 'cow', arabic: 'بقرة', example: 'The cow gives us milk.', category: 'animals', imageUrl: getImageUrl('cow farm'), level: 'beginner' },
  { word: 'sheep', arabic: 'خروف', example: 'The sheep has white wool.', category: 'animals', imageUrl: getImageUrl('sheep wool'), level: 'beginner' },
  { word: 'chicken', arabic: 'دجاجة', example: 'The chicken lays eggs.', category: 'animals', imageUrl: getImageUrl('chicken farm'), level: 'beginner' },
  { word: 'lion', arabic: 'أسد', example: 'The lion is the king of the jungle.', category: 'animals', imageUrl: getImageUrl('lion wild'), level: 'beginner' },
  { word: 'elephant', arabic: 'فيل', example: 'Elephants are very big animals.', category: 'animals', imageUrl: getImageUrl('elephant africa'), level: 'beginner' },
  { word: 'monkey', arabic: 'قرد', example: 'Monkeys love bananas.', category: 'animals', imageUrl: getImageUrl('monkey'), level: 'beginner' },
  { word: 'rabbit', arabic: 'أرنب', example: 'The rabbit has long ears.', category: 'animals', imageUrl: getImageUrl('rabbit bunny'), level: 'beginner' },
  { word: 'bear', arabic: 'دب', example: 'Bears live in the forest.', category: 'animals', imageUrl: getImageUrl('bear forest'), level: 'beginner' },
  { word: 'snake', arabic: 'ثعبان', example: 'Some snakes are dangerous.', category: 'animals', imageUrl: getImageUrl('snake reptile'), level: 'beginner' },
  { word: 'butterfly', arabic: 'فراشة', example: 'The butterfly is colorful.', category: 'animals', imageUrl: getImageUrl('butterfly colorful'), level: 'beginner' },

  // Colors
  { word: 'red', arabic: 'أحمر', example: 'The apple is red.', category: 'colors', imageUrl: getImageUrl('red color'), level: 'beginner' },
  { word: 'blue', arabic: 'أزرق', example: 'The sky is blue today.', category: 'colors', imageUrl: getImageUrl('blue sky'), level: 'beginner' },
  { word: 'green', arabic: 'أخضر', example: 'The grass is green.', category: 'colors', imageUrl: getImageUrl('green nature'), level: 'beginner' },
  { word: 'yellow', arabic: 'أصفر', example: 'The sun is yellow.', category: 'colors', imageUrl: getImageUrl('yellow sunflower'), level: 'beginner' },
  { word: 'orange', arabic: 'برتقالي', example: 'The orange is orange color.', category: 'colors', imageUrl: getImageUrl('orange color'), level: 'beginner' },
  { word: 'purple', arabic: 'بنفسجي', example: 'She wore a purple dress.', category: 'colors', imageUrl: getImageUrl('purple flower'), level: 'beginner' },
  { word: 'pink', arabic: 'وردي', example: 'The flowers are pink.', category: 'colors', imageUrl: getImageUrl('pink rose'), level: 'beginner' },
  { word: 'black', arabic: 'أسود', example: 'The night sky is black.', category: 'colors', imageUrl: getImageUrl('black dark'), level: 'beginner' },
  { word: 'white', arabic: 'أبيض', example: 'Snow is white.', category: 'colors', imageUrl: getImageUrl('white snow'), level: 'beginner' },
  { word: 'brown', arabic: 'بني', example: 'The tree trunk is brown.', category: 'colors', imageUrl: getImageUrl('brown wood'), level: 'beginner' },
  { word: 'gray', arabic: 'رمادي', example: 'The clouds are gray today.', category: 'colors', imageUrl: getImageUrl('gray clouds'), level: 'beginner' },
  { word: 'gold', arabic: 'ذهبي', example: 'The ring is gold.', category: 'colors', imageUrl: getImageUrl('gold jewelry'), level: 'beginner' },

  // Numbers (as words)
  { word: 'one', arabic: 'واحد', example: 'I have one book.', category: 'numbers', imageUrl: getImageUrl('number one'), level: 'beginner' },
  { word: 'two', arabic: 'اثنان', example: 'I have two hands.', category: 'numbers', imageUrl: getImageUrl('number two'), level: 'beginner' },
  { word: 'three', arabic: 'ثلاثة', example: 'There are three apples.', category: 'numbers', imageUrl: getImageUrl('number three'), level: 'beginner' },
  { word: 'four', arabic: 'أربعة', example: 'A car has four wheels.', category: 'numbers', imageUrl: getImageUrl('number four'), level: 'beginner' },
  { word: 'five', arabic: 'خمسة', example: 'I have five fingers.', category: 'numbers', imageUrl: getImageUrl('number five'), level: 'beginner' },
  { word: 'ten', arabic: 'عشرة', example: 'I can count to ten.', category: 'numbers', imageUrl: getImageUrl('number ten'), level: 'beginner' },
  { word: 'hundred', arabic: 'مئة', example: 'There are a hundred students.', category: 'numbers', imageUrl: getImageUrl('hundred'), level: 'beginner' },
  { word: 'thousand', arabic: 'ألف', example: 'This costs one thousand dollars.', category: 'numbers', imageUrl: getImageUrl('thousand'), level: 'beginner' },
  { word: 'first', arabic: 'الأول', example: 'He came first in the race.', category: 'numbers', imageUrl: getImageUrl('first place'), level: 'beginner' },
  { word: 'second', arabic: 'الثاني', example: 'She finished in second place.', category: 'numbers', imageUrl: getImageUrl('second place'), level: 'beginner' },

  // Body Parts
  { word: 'head', arabic: 'رأس', example: 'My head feels heavy.', category: 'body', imageUrl: getImageUrl('head face'), level: 'beginner' },
  { word: 'eye', arabic: 'عين', example: 'I have brown eyes.', category: 'body', imageUrl: getImageUrl('eyes face'), level: 'beginner' },
  { word: 'ear', arabic: 'أذن', example: 'I hear with my ears.', category: 'body', imageUrl: getImageUrl('ear hearing'), level: 'beginner' },
  { word: 'nose', arabic: 'أنف', example: 'I smell with my nose.', category: 'body', imageUrl: getImageUrl('nose face'), level: 'beginner' },
  { word: 'mouth', arabic: 'فم', example: 'I eat with my mouth.', category: 'body', imageUrl: getImageUrl('mouth smile'), level: 'beginner' },
  { word: 'hand', arabic: 'يد', example: 'I write with my hand.', category: 'body', imageUrl: getImageUrl('hand gesture'), level: 'beginner' },
  { word: 'foot', arabic: 'قدم', example: 'I walk with my feet.', category: 'body', imageUrl: getImageUrl('foot walking'), level: 'beginner' },
  { word: 'arm', arabic: 'ذراع', example: 'I use my arms to swim.', category: 'body', imageUrl: getImageUrl('arm muscle'), level: 'beginner' },
  { word: 'leg', arabic: 'ساق', example: 'I run with my legs.', category: 'body', imageUrl: getImageUrl('leg running'), level: 'beginner' },
  { word: 'heart', arabic: 'قلب', example: 'My heart beats fast.', category: 'body', imageUrl: getImageUrl('heart love'), level: 'beginner' },
  { word: 'finger', arabic: 'إصبع', example: 'I have ten fingers.', category: 'body', imageUrl: getImageUrl('finger pointing'), level: 'beginner' },
  { word: 'hair', arabic: 'شعر', example: 'She has long black hair.', category: 'body', imageUrl: getImageUrl('hair beautiful'), level: 'beginner' },
  { word: 'face', arabic: 'وجه', example: 'He has a kind face.', category: 'body', imageUrl: getImageUrl('face smile'), level: 'beginner' },
  { word: 'neck', arabic: 'رقبة', example: 'She wears a necklace.', category: 'body', imageUrl: getImageUrl('neck jewelry'), level: 'beginner' },
  { word: 'back', arabic: 'ظهر', example: 'My back hurts a little.', category: 'body', imageUrl: getImageUrl('back spine'), level: 'beginner' },

  // Home & Furniture
  { word: 'house', arabic: 'بيت', example: 'I live in a big house.', category: 'home', imageUrl: getImageUrl('house home'), level: 'beginner' },
  { word: 'door', arabic: 'باب', example: 'Please close the door.', category: 'home', imageUrl: getImageUrl('door entrance'), level: 'beginner' },
  { word: 'window', arabic: 'نافذة', example: 'Open the window please.', category: 'home', imageUrl: getImageUrl('window room'), level: 'beginner' },
  { word: 'room', arabic: 'غرفة', example: 'This room is very big.', category: 'home', imageUrl: getImageUrl('room interior'), level: 'beginner' },
  { word: 'bed', arabic: 'سرير', example: 'I sleep in my bed.', category: 'home', imageUrl: getImageUrl('bed bedroom'), level: 'beginner' },
  { word: 'chair', arabic: 'كرسي', example: 'Please sit on the chair.', category: 'home', imageUrl: getImageUrl('chair furniture'), level: 'beginner' },
  { word: 'table', arabic: 'طاولة', example: 'Put it on the table.', category: 'home', imageUrl: getImageUrl('table dining'), level: 'beginner' },
  { word: 'kitchen', arabic: 'مطبخ', example: 'I cook in the kitchen.', category: 'home', imageUrl: getImageUrl('kitchen modern'), level: 'beginner' },
  { word: 'bathroom', arabic: 'حمام', example: 'The bathroom is clean.', category: 'home', imageUrl: getImageUrl('bathroom modern'), level: 'beginner' },
  { word: 'garden', arabic: 'حديقة', example: 'The garden is beautiful.', category: 'home', imageUrl: getImageUrl('garden flowers'), level: 'beginner' },
  { word: 'floor', arabic: 'أرضية', example: 'The floor is clean.', category: 'home', imageUrl: getImageUrl('floor clean'), level: 'beginner' },
  { word: 'wall', arabic: 'جدار', example: 'The wall is white.', category: 'home', imageUrl: getImageUrl('wall paint'), level: 'beginner' },
  { word: 'roof', arabic: 'سقف', example: 'The roof needs repair.', category: 'home', imageUrl: getImageUrl('roof house'), level: 'beginner' },
  { word: 'stairs', arabic: 'درج', example: 'I climb the stairs.', category: 'home', imageUrl: getImageUrl('stairs steps'), level: 'beginner' },
  { word: 'lamp', arabic: 'مصباح', example: 'The lamp gives light.', category: 'home', imageUrl: getImageUrl('lamp light'), level: 'beginner' },

  // Weather & Nature
  { word: 'sun', arabic: 'شمس', example: 'The sun is shining bright.', category: 'nature', imageUrl: getImageUrl('sun sunshine'), level: 'beginner' },
  { word: 'moon', arabic: 'قمر', example: 'The moon is full tonight.', category: 'nature', imageUrl: getImageUrl('moon night'), level: 'beginner' },
  { word: 'star', arabic: 'نجم', example: 'The stars are beautiful.', category: 'nature', imageUrl: getImageUrl('stars night sky'), level: 'beginner' },
  { word: 'cloud', arabic: 'سحابة', example: 'The clouds are white.', category: 'nature', imageUrl: getImageUrl('clouds sky'), level: 'beginner' },
  { word: 'rain', arabic: 'مطر', example: 'It is raining today.', category: 'nature', imageUrl: getImageUrl('rain weather'), level: 'beginner' },
  { word: 'snow', arabic: 'ثلج', example: 'Snow covers the ground.', category: 'nature', imageUrl: getImageUrl('snow winter'), level: 'beginner' },
  { word: 'wind', arabic: 'رياح', example: 'The wind is strong today.', category: 'nature', imageUrl: getImageUrl('wind weather'), level: 'beginner' },
  { word: 'tree', arabic: 'شجرة', example: 'The tree is very tall.', category: 'nature', imageUrl: getImageUrl('tree forest'), level: 'beginner' },
  { word: 'flower', arabic: 'زهرة', example: 'The flower smells nice.', category: 'nature', imageUrl: getImageUrl('flower beautiful'), level: 'beginner' },
  { word: 'river', arabic: 'نهر', example: 'The river flows to the sea.', category: 'nature', imageUrl: getImageUrl('river water'), level: 'beginner' },
  { word: 'sea', arabic: 'بحر', example: 'The sea is very deep.', category: 'nature', imageUrl: getImageUrl('sea ocean'), level: 'beginner' },
  { word: 'mountain', arabic: 'جبل', example: 'The mountain is high.', category: 'nature', imageUrl: getImageUrl('mountain landscape'), level: 'beginner' },
  { word: 'sky', arabic: 'سماء', example: 'The sky is blue today.', category: 'nature', imageUrl: getImageUrl('sky clouds'), level: 'beginner' },
  { word: 'beach', arabic: 'شاطئ', example: 'I love the beach.', category: 'nature', imageUrl: getImageUrl('beach sand'), level: 'beginner' },
  { word: 'forest', arabic: 'غابة', example: 'The forest is green.', category: 'nature', imageUrl: getImageUrl('forest trees'), level: 'beginner' },

  // Time & Days
  { word: 'day', arabic: 'يوم', example: 'Have a nice day!', category: 'time', imageUrl: getImageUrl('day sunshine'), level: 'beginner' },
  { word: 'night', arabic: 'ليل', example: 'Good night, sleep well.', category: 'time', imageUrl: getImageUrl('night moon'), level: 'beginner' },
  { word: 'morning', arabic: 'صباح', example: 'I wake up early morning.', category: 'time', imageUrl: getImageUrl('morning sunrise'), level: 'beginner' },
  { word: 'evening', arabic: 'مساء', example: 'Good evening everyone!', category: 'time', imageUrl: getImageUrl('evening sunset'), level: 'beginner' },
  { word: 'today', arabic: 'اليوم', example: 'Today is a great day.', category: 'time', imageUrl: getImageUrl('today calendar'), level: 'beginner' },
  { word: 'tomorrow', arabic: 'غدا', example: 'I will go tomorrow.', category: 'time', imageUrl: getImageUrl('tomorrow future'), level: 'beginner' },
  { word: 'yesterday', arabic: 'أمس', example: 'Yesterday was fun.', category: 'time', imageUrl: getImageUrl('yesterday past'), level: 'beginner' },
  { word: 'week', arabic: 'أسبوع', example: 'I study every week.', category: 'time', imageUrl: getImageUrl('week calendar'), level: 'beginner' },
  { word: 'month', arabic: 'شهر', example: 'Next month is my birthday.', category: 'time', imageUrl: getImageUrl('month calendar'), level: 'beginner' },
  { word: 'year', arabic: 'سنة', example: 'Happy new year!', category: 'time', imageUrl: getImageUrl('year celebration'), level: 'beginner' },
  { word: 'hour', arabic: 'ساعة', example: 'Wait for one hour.', category: 'time', imageUrl: getImageUrl('hour clock'), level: 'beginner' },
  { word: 'minute', arabic: 'دقيقة', example: 'Wait a minute please.', category: 'time', imageUrl: getImageUrl('minute time'), level: 'beginner' },

  // School & Education
  { word: 'school', arabic: 'مدرسة', example: 'I go to school every day.', category: 'education', imageUrl: getImageUrl('school building'), level: 'beginner' },
  { word: 'teacher', arabic: 'معلم', example: 'The teacher is very kind.', category: 'education', imageUrl: getImageUrl('teacher classroom'), level: 'beginner' },
  { word: 'student', arabic: 'طالب', example: 'I am a good student.', category: 'education', imageUrl: getImageUrl('student studying'), level: 'beginner' },
  { word: 'book', arabic: 'كتاب', example: 'I read a book every day.', category: 'education', imageUrl: getImageUrl('book reading'), level: 'beginner' },
  { word: 'pen', arabic: 'قلم', example: 'I write with a pen.', category: 'education', imageUrl: getImageUrl('pen writing'), level: 'beginner' },
  { word: 'pencil', arabic: 'قلم رصاص', example: 'I draw with a pencil.', category: 'education', imageUrl: getImageUrl('pencil drawing'), level: 'beginner' },
  { word: 'paper', arabic: 'ورقة', example: 'I need a piece of paper.', category: 'education', imageUrl: getImageUrl('paper office'), level: 'beginner' },
  { word: 'class', arabic: 'صف', example: 'The class starts at 8.', category: 'education', imageUrl: getImageUrl('classroom students'), level: 'beginner' },
  { word: 'lesson', arabic: 'درس', example: 'This lesson is important.', category: 'education', imageUrl: getImageUrl('lesson learning'), level: 'beginner' },
  { word: 'homework', arabic: 'واجب منزلي', example: 'I finished my homework.', category: 'education', imageUrl: getImageUrl('homework study'), level: 'beginner' },
  { word: 'exam', arabic: 'امتحان', example: 'The exam was easy.', category: 'education', imageUrl: getImageUrl('exam test'), level: 'beginner' },
  { word: 'library', arabic: 'مكتبة', example: 'I study in the library.', category: 'education', imageUrl: getImageUrl('library books'), level: 'beginner' },

  // Transportation
  { word: 'car', arabic: 'سيارة', example: 'I drive my car to work.', category: 'transport', imageUrl: getImageUrl('car driving'), level: 'beginner' },
  { word: 'bus', arabic: 'حافلة', example: 'I take the bus to school.', category: 'transport', imageUrl: getImageUrl('bus transport'), level: 'beginner' },
  { word: 'train', arabic: 'قطار', example: 'The train is fast.', category: 'transport', imageUrl: getImageUrl('train railway'), level: 'beginner' },
  { word: 'plane', arabic: 'طائرة', example: 'The plane flies high.', category: 'transport', imageUrl: getImageUrl('airplane flying'), level: 'beginner' },
  { word: 'bicycle', arabic: 'دراجة', example: 'I ride my bicycle daily.', category: 'transport', imageUrl: getImageUrl('bicycle cycling'), level: 'beginner' },
  { word: 'boat', arabic: 'قارب', example: 'The boat sails on water.', category: 'transport', imageUrl: getImageUrl('boat sailing'), level: 'beginner' },
  { word: 'ship', arabic: 'سفينة', example: 'The ship is very big.', category: 'transport', imageUrl: getImageUrl('ship ocean'), level: 'beginner' },
  { word: 'taxi', arabic: 'تاكسي', example: 'I took a taxi home.', category: 'transport', imageUrl: getImageUrl('taxi car'), level: 'beginner' },
  { word: 'motorcycle', arabic: 'دراجة نارية', example: 'He rides a motorcycle.', category: 'transport', imageUrl: getImageUrl('motorcycle rider'), level: 'beginner' },
  { word: 'airport', arabic: 'مطار', example: 'We are at the airport.', category: 'transport', imageUrl: getImageUrl('airport terminal'), level: 'beginner' },

  // Clothing
  { word: 'shirt', arabic: 'قميص', example: 'I wear a white shirt.', category: 'clothing', imageUrl: getImageUrl('shirt fashion'), level: 'beginner' },
  { word: 'pants', arabic: 'بنطال', example: 'These pants fit well.', category: 'clothing', imageUrl: getImageUrl('pants jeans'), level: 'beginner' },
  { word: 'dress', arabic: 'فستان', example: 'She wears a beautiful dress.', category: 'clothing', imageUrl: getImageUrl('dress fashion'), level: 'beginner' },
  { word: 'shoes', arabic: 'حذاء', example: 'My shoes are new.', category: 'clothing', imageUrl: getImageUrl('shoes fashion'), level: 'beginner' },
  { word: 'hat', arabic: 'قبعة', example: 'He wears a hat in summer.', category: 'clothing', imageUrl: getImageUrl('hat fashion'), level: 'beginner' },
  { word: 'jacket', arabic: 'جاكيت', example: 'I wear a jacket in winter.', category: 'clothing', imageUrl: getImageUrl('jacket winter'), level: 'beginner' },
  { word: 'coat', arabic: 'معطف', example: 'The coat is warm.', category: 'clothing', imageUrl: getImageUrl('coat winter'), level: 'beginner' },
  { word: 'socks', arabic: 'جوارب', example: 'I wear warm socks.', category: 'clothing', imageUrl: getImageUrl('socks colorful'), level: 'beginner' },
  { word: 'gloves', arabic: 'قفازات', example: 'Gloves keep hands warm.', category: 'clothing', imageUrl: getImageUrl('gloves winter'), level: 'beginner' },
  { word: 'scarf', arabic: 'وشاح', example: 'The scarf is colorful.', category: 'clothing', imageUrl: getImageUrl('scarf fashion'), level: 'beginner' },

  // Professions
  { word: 'doctor', arabic: 'طبيب', example: 'The doctor helps sick people.', category: 'professions', imageUrl: getImageUrl('doctor medical'), level: 'beginner' },
  { word: 'nurse', arabic: 'ممرضة', example: 'The nurse is very caring.', category: 'professions', imageUrl: getImageUrl('nurse hospital'), level: 'beginner' },
  { word: 'engineer', arabic: 'مهندس', example: 'The engineer builds bridges.', category: 'professions', imageUrl: getImageUrl('engineer construction'), level: 'beginner' },
  { word: 'police', arabic: 'شرطي', example: 'The police help people.', category: 'professions', imageUrl: getImageUrl('police officer'), level: 'beginner' },
  { word: 'chef', arabic: 'طباخ', example: 'The chef cooks great food.', category: 'professions', imageUrl: getImageUrl('chef cooking'), level: 'beginner' },
  { word: 'driver', arabic: 'سائق', example: 'The driver is careful.', category: 'professions', imageUrl: getImageUrl('driver car'), level: 'beginner' },
  { word: 'pilot', arabic: 'طيار', example: 'The pilot flies planes.', category: 'professions', imageUrl: getImageUrl('pilot airplane'), level: 'beginner' },
  { word: 'farmer', arabic: 'مزارع', example: 'The farmer grows food.', category: 'professions', imageUrl: getImageUrl('farmer farm'), level: 'beginner' },
  { word: 'dentist', arabic: 'طبيب أسنان', example: 'The dentist checks my teeth.', category: 'professions', imageUrl: getImageUrl('dentist teeth'), level: 'beginner' },
  { word: 'lawyer', arabic: 'محامي', example: 'The lawyer works in court.', category: 'professions', imageUrl: getImageUrl('lawyer court'), level: 'beginner' },

  // Verbs (Actions)
  { word: 'eat', arabic: 'يأكل', example: 'I eat breakfast at 7 AM.', category: 'verbs', imageUrl: getImageUrl('eating food'), level: 'beginner' },
  { word: 'drink', arabic: 'يشرب', example: 'I drink water every day.', category: 'verbs', imageUrl: getImageUrl('drinking water'), level: 'beginner' },
  { word: 'sleep', arabic: 'ينام', example: 'I sleep at night.', category: 'verbs', imageUrl: getImageUrl('sleeping bed'), level: 'beginner' },
  { word: 'walk', arabic: 'يمشي', example: 'I walk to school.', category: 'verbs', imageUrl: getImageUrl('walking park'), level: 'beginner' },
  { word: 'run', arabic: 'يركض', example: 'I run in the morning.', category: 'verbs', imageUrl: getImageUrl('running exercise'), level: 'beginner' },
  { word: 'read', arabic: 'يقرأ', example: 'I read books every day.', category: 'verbs', imageUrl: getImageUrl('reading book'), level: 'beginner' },
  { word: 'write', arabic: 'يكتب', example: 'I write in my notebook.', category: 'verbs', imageUrl: getImageUrl('writing paper'), level: 'beginner' },
  { word: 'speak', arabic: 'يتكلم', example: 'I speak English well.', category: 'verbs', imageUrl: getImageUrl('speaking talking'), level: 'beginner' },
  { word: 'listen', arabic: 'يستمع', example: 'I listen to music.', category: 'verbs', imageUrl: getImageUrl('listening music'), level: 'beginner' },
  { word: 'watch', arabic: 'يشاهد', example: 'I watch TV at night.', category: 'verbs', imageUrl: getImageUrl('watching tv'), level: 'beginner' },
  { word: 'play', arabic: 'يلعب', example: 'I play football.', category: 'verbs', imageUrl: getImageUrl('playing sports'), level: 'beginner' },
  { word: 'work', arabic: 'يعمل', example: 'I work from home.', category: 'verbs', imageUrl: getImageUrl('working office'), level: 'beginner' },
  { word: 'study', arabic: 'يدرس', example: 'I study English daily.', category: 'verbs', imageUrl: getImageUrl('studying books'), level: 'beginner' },
  { word: 'cook', arabic: 'يطبخ', example: 'I cook dinner every day.', category: 'verbs', imageUrl: getImageUrl('cooking kitchen'), level: 'beginner' },
  { word: 'clean', arabic: 'ينظف', example: 'I clean my room.', category: 'verbs', imageUrl: getImageUrl('cleaning room'), level: 'beginner' },
  { word: 'buy', arabic: 'يشتري', example: 'I buy groceries weekly.', category: 'verbs', imageUrl: getImageUrl('shopping buying'), level: 'beginner' },
  { word: 'sell', arabic: 'يبيع', example: 'He sells fruits.', category: 'verbs', imageUrl: getImageUrl('selling market'), level: 'beginner' },
  { word: 'open', arabic: 'يفتح', example: 'Open the door please.', category: 'verbs', imageUrl: getImageUrl('opening door'), level: 'beginner' },
  { word: 'close', arabic: 'يغلق', example: 'Close the window.', category: 'verbs', imageUrl: getImageUrl('closing window'), level: 'beginner' },
  { word: 'come', arabic: 'يأتي', example: 'Come here please.', category: 'verbs', imageUrl: getImageUrl('coming walking'), level: 'beginner' },
  { word: 'go', arabic: 'يذهب', example: 'I go to work at 8.', category: 'verbs', imageUrl: getImageUrl('going walking'), level: 'beginner' },
  { word: 'sit', arabic: 'يجلس', example: 'Please sit down.', category: 'verbs', imageUrl: getImageUrl('sitting chair'), level: 'beginner' },
  { word: 'stand', arabic: 'يقف', example: 'Please stand up.', category: 'verbs', imageUrl: getImageUrl('standing person'), level: 'beginner' },
  { word: 'help', arabic: 'يساعد', example: 'Can you help me?', category: 'verbs', imageUrl: getImageUrl('helping hands'), level: 'beginner' },
  { word: 'love', arabic: 'يحب', example: 'I love my family.', category: 'verbs', imageUrl: getImageUrl('love heart'), level: 'beginner' },

  // Adjectives
  { word: 'big', arabic: 'كبير', example: 'The elephant is big.', category: 'adjectives', imageUrl: getImageUrl('big large'), level: 'beginner' },
  { word: 'small', arabic: 'صغير', example: 'The ant is small.', category: 'adjectives', imageUrl: getImageUrl('small tiny'), level: 'beginner' },
  { word: 'hot', arabic: 'حار', example: 'The coffee is hot.', category: 'adjectives', imageUrl: getImageUrl('hot summer'), level: 'beginner' },
  { word: 'cold', arabic: 'بارد', example: 'The ice is cold.', category: 'adjectives', imageUrl: getImageUrl('cold winter'), level: 'beginner' },
  { word: 'happy', arabic: 'سعيد', example: 'I am very happy.', category: 'adjectives', imageUrl: getImageUrl('happy smile'), level: 'beginner' },
  { word: 'sad', arabic: 'حزين', example: 'He looks sad today.', category: 'adjectives', imageUrl: getImageUrl('sad emotion'), level: 'beginner' },
  { word: 'fast', arabic: 'سريع', example: 'The car is fast.', category: 'adjectives', imageUrl: getImageUrl('fast speed'), level: 'beginner' },
  { word: 'slow', arabic: 'بطيء', example: 'The turtle is slow.', category: 'adjectives', imageUrl: getImageUrl('slow turtle'), level: 'beginner' },
  { word: 'beautiful', arabic: 'جميل', example: 'The sunset is beautiful.', category: 'adjectives', imageUrl: getImageUrl('beautiful sunset'), level: 'beginner' },
  { word: 'ugly', arabic: 'قبيح', example: 'The monster is ugly.', category: 'adjectives', imageUrl: getImageUrl('ugly scary'), level: 'beginner' },
  { word: 'good', arabic: 'جيد', example: 'This food is good.', category: 'adjectives', imageUrl: getImageUrl('good thumbs up'), level: 'beginner' },
  { word: 'bad', arabic: 'سيء', example: 'The weather is bad.', category: 'adjectives', imageUrl: getImageUrl('bad weather'), level: 'beginner' },
  { word: 'new', arabic: 'جديد', example: 'I have a new phone.', category: 'adjectives', imageUrl: getImageUrl('new modern'), level: 'beginner' },
  { word: 'old', arabic: 'قديم', example: 'This house is old.', category: 'adjectives', imageUrl: getImageUrl('old antique'), level: 'beginner' },
  { word: 'easy', arabic: 'سهل', example: 'This test is easy.', category: 'adjectives', imageUrl: getImageUrl('easy simple'), level: 'beginner' },
  { word: 'difficult', arabic: 'صعب', example: 'Math is difficult.', category: 'adjectives', imageUrl: getImageUrl('difficult hard'), level: 'beginner' },
  { word: 'clean', arabic: 'نظيف', example: 'The room is clean.', category: 'adjectives', imageUrl: getImageUrl('clean tidy'), level: 'beginner' },
  { word: 'dirty', arabic: 'متسخ', example: 'The clothes are dirty.', category: 'adjectives', imageUrl: getImageUrl('dirty messy'), level: 'beginner' },
  { word: 'rich', arabic: 'غني', example: 'He is very rich.', category: 'adjectives', imageUrl: getImageUrl('rich wealthy'), level: 'beginner' },
  { word: 'poor', arabic: 'فقير', example: 'They are poor but happy.', category: 'adjectives', imageUrl: getImageUrl('poor humble'), level: 'beginner' },

  // ============ INTERMEDIATE LEVEL ============
  // Business & Work
  { word: 'meeting', arabic: 'اجتماع', example: 'We have a meeting at 3 PM.', category: 'business', imageUrl: getImageUrl('business meeting'), level: 'intermediate' },
  { word: 'salary', arabic: 'راتب', example: 'My salary is good.', category: 'business', imageUrl: getImageUrl('salary money'), level: 'intermediate' },
  { word: 'contract', arabic: 'عقد', example: 'Sign the contract please.', category: 'business', imageUrl: getImageUrl('contract signing'), level: 'intermediate' },
  { word: 'project', arabic: 'مشروع', example: 'We completed the project.', category: 'business', imageUrl: getImageUrl('project work'), level: 'intermediate' },
  { word: 'deadline', arabic: 'موعد نهائي', example: 'The deadline is tomorrow.', category: 'business', imageUrl: getImageUrl('deadline calendar'), level: 'intermediate' },
  { word: 'employee', arabic: 'موظف', example: 'He is a good employee.', category: 'business', imageUrl: getImageUrl('employee office'), level: 'intermediate' },
  { word: 'manager', arabic: 'مدير', example: 'The manager is busy.', category: 'business', imageUrl: getImageUrl('manager business'), level: 'intermediate' },
  { word: 'client', arabic: 'عميل', example: 'The client is satisfied.', category: 'business', imageUrl: getImageUrl('client business'), level: 'intermediate' },
  { word: 'budget', arabic: 'ميزانية', example: 'We exceeded the budget.', category: 'business', imageUrl: getImageUrl('budget money'), level: 'intermediate' },
  { word: 'investment', arabic: 'استثمار', example: 'This is a good investment.', category: 'business', imageUrl: getImageUrl('investment money'), level: 'intermediate' },
  { word: 'profit', arabic: 'ربح', example: 'The profit increased this year.', category: 'business', imageUrl: getImageUrl('profit growth'), level: 'intermediate' },
  { word: 'loss', arabic: 'خسارة', example: 'The company made a loss.', category: 'business', imageUrl: getImageUrl('loss decline'), level: 'intermediate' },
  { word: 'competition', arabic: 'منافسة', example: 'The competition is strong.', category: 'business', imageUrl: getImageUrl('competition business'), level: 'intermediate' },
  { word: 'strategy', arabic: 'استراتيجية', example: 'We need a new strategy.', category: 'business', imageUrl: getImageUrl('strategy planning'), level: 'intermediate' },
  { word: 'negotiation', arabic: 'تفاوض', example: 'The negotiation was successful.', category: 'business', imageUrl: getImageUrl('negotiation business'), level: 'intermediate' },

  // Technology
  { word: 'computer', arabic: 'حاسوب', example: 'I work on my computer.', category: 'technology', imageUrl: getImageUrl('computer laptop'), level: 'intermediate' },
  { word: 'internet', arabic: 'إنترنت', example: 'The internet is fast.', category: 'technology', imageUrl: getImageUrl('internet connection'), level: 'intermediate' },
  { word: 'website', arabic: 'موقع إلكتروني', example: 'Visit our website.', category: 'technology', imageUrl: getImageUrl('website design'), level: 'intermediate' },
  { word: 'software', arabic: 'برنامج', example: 'Install this software.', category: 'technology', imageUrl: getImageUrl('software code'), level: 'intermediate' },
  { word: 'application', arabic: 'تطبيق', example: 'Download the application.', category: 'technology', imageUrl: getImageUrl('app mobile'), level: 'intermediate' },
  { word: 'database', arabic: 'قاعدة بيانات', example: 'The database is updated.', category: 'technology', imageUrl: getImageUrl('database server'), level: 'intermediate' },
  { word: 'password', arabic: 'كلمة مرور', example: 'Change your password.', category: 'technology', imageUrl: getImageUrl('password security'), level: 'intermediate' },
  { word: 'download', arabic: 'تحميل', example: 'Download the file here.', category: 'technology', imageUrl: getImageUrl('download arrow'), level: 'intermediate' },
  { word: 'upload', arabic: 'رفع', example: 'Upload your photo.', category: 'technology', imageUrl: getImageUrl('upload cloud'), level: 'intermediate' },
  { word: 'network', arabic: 'شبكة', example: 'Connect to the network.', category: 'technology', imageUrl: getImageUrl('network connection'), level: 'intermediate' },
  { word: 'device', arabic: 'جهاز', example: 'Turn off the device.', category: 'technology', imageUrl: getImageUrl('device gadget'), level: 'intermediate' },
  { word: 'screen', arabic: 'شاشة', example: 'The screen is bright.', category: 'technology', imageUrl: getImageUrl('screen monitor'), level: 'intermediate' },
  { word: 'keyboard', arabic: 'لوحة مفاتيح', example: 'Use the keyboard to type.', category: 'technology', imageUrl: getImageUrl('keyboard computer'), level: 'intermediate' },
  { word: 'mouse', arabic: 'فأرة', example: 'Click with the mouse.', category: 'technology', imageUrl: getImageUrl('mouse computer'), level: 'intermediate' },
  { word: 'printer', arabic: 'طابعة', example: 'Print using the printer.', category: 'technology', imageUrl: getImageUrl('printer office'), level: 'intermediate' },

  // Health & Medicine
  { word: 'medicine', arabic: 'دواء', example: 'Take your medicine daily.', category: 'health', imageUrl: getImageUrl('medicine pills'), level: 'intermediate' },
  { word: 'hospital', arabic: 'مستشفى', example: 'He is in the hospital.', category: 'health', imageUrl: getImageUrl('hospital building'), level: 'intermediate' },
  { word: 'disease', arabic: 'مرض', example: 'This disease is curable.', category: 'health', imageUrl: getImageUrl('disease medical'), level: 'intermediate' },
  { word: 'treatment', arabic: 'علاج', example: 'The treatment is working.', category: 'health', imageUrl: getImageUrl('treatment medical'), level: 'intermediate' },
  { word: 'symptom', arabic: 'عرض', example: 'What are the symptoms?', category: 'health', imageUrl: getImageUrl('symptom sick'), level: 'intermediate' },
  { word: 'diagnosis', arabic: 'تشخيص', example: 'The diagnosis was correct.', category: 'health', imageUrl: getImageUrl('diagnosis doctor'), level: 'intermediate' },
  { word: 'surgery', arabic: 'جراحة', example: 'The surgery was successful.', category: 'health', imageUrl: getImageUrl('surgery operation'), level: 'intermediate' },
  { word: 'prescription', arabic: 'وصفة طبية', example: 'Here is your prescription.', category: 'health', imageUrl: getImageUrl('prescription medicine'), level: 'intermediate' },
  { word: 'vaccine', arabic: 'لقاح', example: 'Get your vaccine soon.', category: 'health', imageUrl: getImageUrl('vaccine injection'), level: 'intermediate' },
  { word: 'allergy', arabic: 'حساسية', example: 'I have a food allergy.', category: 'health', imageUrl: getImageUrl('allergy sneeze'), level: 'intermediate' },
  { word: 'infection', arabic: 'عدوى', example: 'The infection is spreading.', category: 'health', imageUrl: getImageUrl('infection medical'), level: 'intermediate' },
  { word: 'fever', arabic: 'حمى', example: 'She has a high fever.', category: 'health', imageUrl: getImageUrl('fever thermometer'), level: 'intermediate' },
  { word: 'headache', arabic: 'صداع', example: 'I have a bad headache.', category: 'health', imageUrl: getImageUrl('headache pain'), level: 'intermediate' },
  { word: 'pain', arabic: 'ألم', example: 'I feel pain in my leg.', category: 'health', imageUrl: getImageUrl('pain hurt'), level: 'intermediate' },
  { word: 'exercise', arabic: 'تمرين', example: 'Exercise is good for health.', category: 'health', imageUrl: getImageUrl('exercise fitness'), level: 'intermediate' },

  // Travel & Tourism
  { word: 'passport', arabic: 'جواز سفر', example: 'Show your passport please.', category: 'travel', imageUrl: getImageUrl('passport travel'), level: 'intermediate' },
  { word: 'ticket', arabic: 'تذكرة', example: 'Buy your ticket online.', category: 'travel', imageUrl: getImageUrl('ticket travel'), level: 'intermediate' },
  { word: 'luggage', arabic: 'أمتعة', example: 'Check in your luggage.', category: 'travel', imageUrl: getImageUrl('luggage suitcase'), level: 'intermediate' },
  { word: 'reservation', arabic: 'حجز', example: 'Make a reservation first.', category: 'travel', imageUrl: getImageUrl('reservation booking'), level: 'intermediate' },
  { word: 'tourist', arabic: 'سائح', example: 'Many tourists visit here.', category: 'travel', imageUrl: getImageUrl('tourist sightseeing'), level: 'intermediate' },
  { word: 'destination', arabic: 'وجهة', example: 'What is your destination?', category: 'travel', imageUrl: getImageUrl('destination travel'), level: 'intermediate' },
  { word: 'departure', arabic: 'مغادرة', example: 'The departure is at 5 PM.', category: 'travel', imageUrl: getImageUrl('departure airport'), level: 'intermediate' },
  { word: 'arrival', arabic: 'وصول', example: 'The arrival is delayed.', category: 'travel', imageUrl: getImageUrl('arrival airport'), level: 'intermediate' },
  { word: 'journey', arabic: 'رحلة', example: 'The journey was pleasant.', category: 'travel', imageUrl: getImageUrl('journey adventure'), level: 'intermediate' },
  { word: 'accommodation', arabic: 'إقامة', example: 'Book accommodation early.', category: 'travel', imageUrl: getImageUrl('accommodation hotel'), level: 'intermediate' },
  { word: 'currency', arabic: 'عملة', example: 'Exchange your currency here.', category: 'travel', imageUrl: getImageUrl('currency money'), level: 'intermediate' },
  { word: 'customs', arabic: 'جمارك', example: 'Go through customs first.', category: 'travel', imageUrl: getImageUrl('customs airport'), level: 'intermediate' },
  { word: 'visa', arabic: 'تأشيرة', example: 'You need a visa to enter.', category: 'travel', imageUrl: getImageUrl('visa passport'), level: 'intermediate' },
  { word: 'itinerary', arabic: 'خط سير الرحلة', example: 'Check your itinerary.', category: 'travel', imageUrl: getImageUrl('itinerary plan'), level: 'intermediate' },
  { word: 'souvenir', arabic: 'تذكار', example: 'I bought a souvenir.', category: 'travel', imageUrl: getImageUrl('souvenir gift'), level: 'intermediate' },

  // Environment
  { word: 'environment', arabic: 'بيئة', example: 'Protect the environment.', category: 'environment', imageUrl: getImageUrl('environment nature'), level: 'intermediate' },
  { word: 'pollution', arabic: 'تلوث', example: 'Pollution is a problem.', category: 'environment', imageUrl: getImageUrl('pollution smog'), level: 'intermediate' },
  { word: 'climate', arabic: 'مناخ', example: 'The climate is changing.', category: 'environment', imageUrl: getImageUrl('climate weather'), level: 'intermediate' },
  { word: 'recycling', arabic: 'إعادة تدوير', example: 'Recycling helps the planet.', category: 'environment', imageUrl: getImageUrl('recycling green'), level: 'intermediate' },
  { word: 'conservation', arabic: 'حفظ', example: 'Conservation is important.', category: 'environment', imageUrl: getImageUrl('conservation nature'), level: 'intermediate' },
  { word: 'ecosystem', arabic: 'نظام بيئي', example: 'The ecosystem is fragile.', category: 'environment', imageUrl: getImageUrl('ecosystem nature'), level: 'intermediate' },
  { word: 'wildlife', arabic: 'حياة برية', example: 'Protect the wildlife.', category: 'environment', imageUrl: getImageUrl('wildlife animals'), level: 'intermediate' },
  { word: 'sustainable', arabic: 'مستدام', example: 'Use sustainable energy.', category: 'environment', imageUrl: getImageUrl('sustainable energy'), level: 'intermediate' },
  { word: 'renewable', arabic: 'متجدد', example: 'Renewable energy is clean.', category: 'environment', imageUrl: getImageUrl('renewable solar'), level: 'intermediate' },
  { word: 'carbon', arabic: 'كربون', example: 'Reduce carbon emissions.', category: 'environment', imageUrl: getImageUrl('carbon footprint'), level: 'intermediate' },
  { word: 'habitat', arabic: 'موطن', example: 'Animals need their habitat.', category: 'environment', imageUrl: getImageUrl('habitat nature'), level: 'intermediate' },
  { word: 'species', arabic: 'أنواع', example: 'Many species are endangered.', category: 'environment', imageUrl: getImageUrl('species animals'), level: 'intermediate' },
  { word: 'deforestation', arabic: 'إزالة الغابات', example: 'Deforestation harms nature.', category: 'environment', imageUrl: getImageUrl('deforestation forest'), level: 'intermediate' },
  { word: 'biodiversity', arabic: 'تنوع حيوي', example: 'Biodiversity is essential.', category: 'environment', imageUrl: getImageUrl('biodiversity nature'), level: 'intermediate' },
  { word: 'organic', arabic: 'عضوي', example: 'Buy organic food.', category: 'environment', imageUrl: getImageUrl('organic food'), level: 'intermediate' },

  // Emotions & Feelings
  { word: 'anxious', arabic: 'قلق', example: 'I feel anxious about the exam.', category: 'emotions', imageUrl: getImageUrl('anxious worried'), level: 'intermediate' },
  { word: 'excited', arabic: 'متحمس', example: 'I am excited about the trip.', category: 'emotions', imageUrl: getImageUrl('excited happy'), level: 'intermediate' },
  { word: 'frustrated', arabic: 'محبط', example: 'He is frustrated with work.', category: 'emotions', imageUrl: getImageUrl('frustrated angry'), level: 'intermediate' },
  { word: 'confident', arabic: 'واثق', example: 'She is very confident.', category: 'emotions', imageUrl: getImageUrl('confident person'), level: 'intermediate' },
  { word: 'nervous', arabic: 'متوتر', example: 'I am nervous about the interview.', category: 'emotions', imageUrl: getImageUrl('nervous anxiety'), level: 'intermediate' },
  { word: 'relieved', arabic: 'مرتاح', example: 'I am relieved it is over.', category: 'emotions', imageUrl: getImageUrl('relieved happy'), level: 'intermediate' },
  { word: 'disappointed', arabic: 'خائب الأمل', example: 'I am disappointed with the result.', category: 'emotions', imageUrl: getImageUrl('disappointed sad'), level: 'intermediate' },
  { word: 'grateful', arabic: 'ممتن', example: 'I am grateful for your help.', category: 'emotions', imageUrl: getImageUrl('grateful thankful'), level: 'intermediate' },
  { word: 'jealous', arabic: 'غيور', example: 'She is jealous of her sister.', category: 'emotions', imageUrl: getImageUrl('jealous envy'), level: 'intermediate' },
  { word: 'proud', arabic: 'فخور', example: 'I am proud of my son.', category: 'emotions', imageUrl: getImageUrl('proud achievement'), level: 'intermediate' },
  { word: 'ashamed', arabic: 'خجول', example: 'He feels ashamed of his mistake.', category: 'emotions', imageUrl: getImageUrl('ashamed shy'), level: 'intermediate' },
  { word: 'curious', arabic: 'فضولي', example: 'The child is very curious.', category: 'emotions', imageUrl: getImageUrl('curious wondering'), level: 'intermediate' },
  { word: 'lonely', arabic: 'وحيد', example: 'She feels lonely sometimes.', category: 'emotions', imageUrl: getImageUrl('lonely alone'), level: 'intermediate' },
  { word: 'hopeful', arabic: 'متفائل', example: 'I am hopeful for the future.', category: 'emotions', imageUrl: getImageUrl('hopeful optimistic'), level: 'intermediate' },
  { word: 'overwhelmed', arabic: 'مثقل', example: 'I feel overwhelmed with work.', category: 'emotions', imageUrl: getImageUrl('overwhelmed stress'), level: 'intermediate' },

  // Sports & Fitness
  { word: 'athlete', arabic: 'رياضي', example: 'He is a professional athlete.', category: 'sports', imageUrl: getImageUrl('athlete sports'), level: 'intermediate' },
  { word: 'championship', arabic: 'بطولة', example: 'They won the championship.', category: 'sports', imageUrl: getImageUrl('championship trophy'), level: 'intermediate' },
  { word: 'tournament', arabic: 'دورة', example: 'The tournament starts Friday.', category: 'sports', imageUrl: getImageUrl('tournament sports'), level: 'intermediate' },
  { word: 'score', arabic: 'نتيجة', example: 'The score is 3 to 1.', category: 'sports', imageUrl: getImageUrl('score game'), level: 'intermediate' },
  { word: 'coach', arabic: 'مدرب', example: 'The coach trains the team.', category: 'sports', imageUrl: getImageUrl('coach training'), level: 'intermediate' },
  { word: 'stadium', arabic: 'ملعب', example: 'The stadium is full.', category: 'sports', imageUrl: getImageUrl('stadium sports'), level: 'intermediate' },
  { word: 'referee', arabic: 'حكم', example: 'The referee made a decision.', category: 'sports', imageUrl: getImageUrl('referee sports'), level: 'intermediate' },
  { word: 'opponent', arabic: 'خصم', example: 'Respect your opponent.', category: 'sports', imageUrl: getImageUrl('opponent competition'), level: 'intermediate' },
  { word: 'victory', arabic: 'انتصار', example: 'They celebrated their victory.', category: 'sports', imageUrl: getImageUrl('victory celebration'), level: 'intermediate' },
  { word: 'defeat', arabic: 'هزيمة', example: 'They accepted the defeat.', category: 'sports', imageUrl: getImageUrl('defeat loss'), level: 'intermediate' },
  { word: 'performance', arabic: 'أداء', example: 'His performance was excellent.', category: 'sports', imageUrl: getImageUrl('performance sports'), level: 'intermediate' },
  { word: 'training', arabic: 'تدريب', example: 'Training starts early.', category: 'sports', imageUrl: getImageUrl('training gym'), level: 'intermediate' },
  { word: 'fitness', arabic: 'لياقة', example: 'Fitness is important.', category: 'sports', imageUrl: getImageUrl('fitness gym'), level: 'intermediate' },
  { word: 'marathon', arabic: 'ماراثون', example: 'I ran a marathon.', category: 'sports', imageUrl: getImageUrl('marathon running'), level: 'intermediate' },
  { word: 'equipment', arabic: 'معدات', example: 'Bring your equipment.', category: 'sports', imageUrl: getImageUrl('equipment sports'), level: 'intermediate' },

  // Arts & Entertainment
  { word: 'concert', arabic: 'حفلة موسيقية', example: 'We attended a concert.', category: 'arts', imageUrl: getImageUrl('concert music'), level: 'intermediate' },
  { word: 'exhibition', arabic: 'معرض', example: 'The art exhibition is amazing.', category: 'arts', imageUrl: getImageUrl('exhibition art'), level: 'intermediate' },
  { word: 'performance', arabic: 'عرض', example: 'The performance was stunning.', category: 'arts', imageUrl: getImageUrl('performance theater'), level: 'intermediate' },
  { word: 'sculpture', arabic: 'نحت', example: 'The sculpture is beautiful.', category: 'arts', imageUrl: getImageUrl('sculpture art'), level: 'intermediate' },
  { word: 'painting', arabic: 'لوحة', example: 'This painting is famous.', category: 'arts', imageUrl: getImageUrl('painting art'), level: 'intermediate' },
  { word: 'gallery', arabic: 'معرض فني', example: 'Visit the art gallery.', category: 'arts', imageUrl: getImageUrl('gallery art'), level: 'intermediate' },
  { word: 'audience', arabic: 'جمهور', example: 'The audience applauded.', category: 'arts', imageUrl: getImageUrl('audience crowd'), level: 'intermediate' },
  { word: 'director', arabic: 'مخرج', example: 'The director won an award.', category: 'arts', imageUrl: getImageUrl('director film'), level: 'intermediate' },
  { word: 'actor', arabic: 'ممثل', example: 'He is a famous actor.', category: 'arts', imageUrl: getImageUrl('actor theater'), level: 'intermediate' },
  { word: 'comedy', arabic: 'كوميديا', example: 'I love comedy movies.', category: 'arts', imageUrl: getImageUrl('comedy funny'), level: 'intermediate' },
  { word: 'drama', arabic: 'دراما', example: 'This is a good drama.', category: 'arts', imageUrl: getImageUrl('drama theater'), level: 'intermediate' },
  { word: 'documentary', arabic: 'وثائقي', example: 'Watch this documentary.', category: 'arts', imageUrl: getImageUrl('documentary film'), level: 'intermediate' },
  { word: 'photography', arabic: 'تصوير', example: 'Photography is my hobby.', category: 'arts', imageUrl: getImageUrl('photography camera'), level: 'intermediate' },
  { word: 'entertainment', arabic: 'ترفيه', example: 'Entertainment is important.', category: 'arts', imageUrl: getImageUrl('entertainment fun'), level: 'intermediate' },
  { word: 'celebrity', arabic: 'مشهور', example: 'She is a celebrity.', category: 'arts', imageUrl: getImageUrl('celebrity famous'), level: 'intermediate' },

  // ============ ADVANCED LEVEL ============
  // Academic & Research
  { word: 'hypothesis', arabic: 'فرضية', example: 'The hypothesis was proven correct.', category: 'academic', imageUrl: getImageUrl('hypothesis science'), level: 'advanced' },
  { word: 'methodology', arabic: 'منهجية', example: 'Explain your methodology clearly.', category: 'academic', imageUrl: getImageUrl('methodology research'), level: 'advanced' },
  { word: 'analysis', arabic: 'تحليل', example: 'The data analysis is complete.', category: 'academic', imageUrl: getImageUrl('analysis data'), level: 'advanced' },
  { word: 'synthesis', arabic: 'تركيب', example: 'The synthesis of ideas was excellent.', category: 'academic', imageUrl: getImageUrl('synthesis combine'), level: 'advanced' },
  { word: 'dissertation', arabic: 'أطروحة', example: 'She defended her dissertation.', category: 'academic', imageUrl: getImageUrl('dissertation thesis'), level: 'advanced' },
  { word: 'abstract', arabic: 'ملخص', example: 'Read the abstract first.', category: 'academic', imageUrl: getImageUrl('abstract summary'), level: 'advanced' },
  { word: 'citation', arabic: 'اقتباس', example: 'Include proper citations.', category: 'academic', imageUrl: getImageUrl('citation reference'), level: 'advanced' },
  { word: 'empirical', arabic: 'تجريبي', example: 'The study is empirical.', category: 'academic', imageUrl: getImageUrl('empirical experiment'), level: 'advanced' },
  { word: 'theoretical', arabic: 'نظري', example: 'This is theoretical knowledge.', category: 'academic', imageUrl: getImageUrl('theoretical concept'), level: 'advanced' },
  { word: 'paradigm', arabic: 'نموذج', example: 'This shifts the paradigm.', category: 'academic', imageUrl: getImageUrl('paradigm model'), level: 'advanced' },
  { word: 'phenomenon', arabic: 'ظاهرة', example: 'This phenomenon is rare.', category: 'academic', imageUrl: getImageUrl('phenomenon nature'), level: 'advanced' },
  { word: 'correlation', arabic: 'ارتباط', example: 'There is a strong correlation.', category: 'academic', imageUrl: getImageUrl('correlation data'), level: 'advanced' },
  { word: 'variable', arabic: 'متغير', example: 'Control the variables carefully.', category: 'academic', imageUrl: getImageUrl('variable science'), level: 'advanced' },
  { word: 'quantitative', arabic: 'كمي', example: 'Use quantitative methods.', category: 'academic', imageUrl: getImageUrl('quantitative numbers'), level: 'advanced' },
  { word: 'qualitative', arabic: 'نوعي', example: 'Qualitative research is valuable.', category: 'academic', imageUrl: getImageUrl('qualitative research'), level: 'advanced' },

  // Law & Politics
  { word: 'legislation', arabic: 'تشريع', example: 'New legislation was passed.', category: 'politics', imageUrl: getImageUrl('legislation law'), level: 'advanced' },
  { word: 'amendment', arabic: 'تعديل', example: 'The amendment was approved.', category: 'politics', imageUrl: getImageUrl('amendment law'), level: 'advanced' },
  { word: 'constitution', arabic: 'دستور', example: 'Read the constitution.', category: 'politics', imageUrl: getImageUrl('constitution law'), level: 'advanced' },
  { word: 'democracy', arabic: 'ديمقراطية', example: 'Democracy is important.', category: 'politics', imageUrl: getImageUrl('democracy vote'), level: 'advanced' },
  { word: 'sovereignty', arabic: 'سيادة', example: 'Respect national sovereignty.', category: 'politics', imageUrl: getImageUrl('sovereignty nation'), level: 'advanced' },
  { word: 'judiciary', arabic: 'قضاء', example: 'The judiciary is independent.', category: 'politics', imageUrl: getImageUrl('judiciary court'), level: 'advanced' },
  { word: 'parliament', arabic: 'برلمان', example: 'Parliament is in session.', category: 'politics', imageUrl: getImageUrl('parliament government'), level: 'advanced' },
  { word: 'diplomacy', arabic: 'دبلوماسية', example: 'Diplomacy resolved the conflict.', category: 'politics', imageUrl: getImageUrl('diplomacy international'), level: 'advanced' },
  { word: 'sanction', arabic: 'عقوبة', example: 'Economic sanctions were imposed.', category: 'politics', imageUrl: getImageUrl('sanction penalty'), level: 'advanced' },
  { word: 'treaty', arabic: 'معاهدة', example: 'They signed a peace treaty.', category: 'politics', imageUrl: getImageUrl('treaty agreement'), level: 'advanced' },
  { word: 'referendum', arabic: 'استفتاء', example: 'The referendum will be held soon.', category: 'politics', imageUrl: getImageUrl('referendum vote'), level: 'advanced' },
  { word: 'bureaucracy', arabic: 'بيروقراطية', example: 'Bureaucracy slows progress.', category: 'politics', imageUrl: getImageUrl('bureaucracy office'), level: 'advanced' },
  { word: 'jurisdiction', arabic: 'ولاية قضائية', example: 'This is under our jurisdiction.', category: 'politics', imageUrl: getImageUrl('jurisdiction law'), level: 'advanced' },
  { word: 'advocacy', arabic: 'مناصرة', example: 'She works in advocacy.', category: 'politics', imageUrl: getImageUrl('advocacy support'), level: 'advanced' },
  { word: 'lobbyist', arabic: 'جماعة ضغط', example: 'Lobbyists influence policy.', category: 'politics', imageUrl: getImageUrl('lobbyist politics'), level: 'advanced' },

  // Economics & Finance
  { word: 'inflation', arabic: 'تضخم', example: 'Inflation is rising.', category: 'economics', imageUrl: getImageUrl('inflation economy'), level: 'advanced' },
  { word: 'recession', arabic: 'ركود', example: 'The recession affected jobs.', category: 'economics', imageUrl: getImageUrl('recession economy'), level: 'advanced' },
  { word: 'commodity', arabic: 'سلعة', example: 'Oil is a valuable commodity.', category: 'economics', imageUrl: getImageUrl('commodity trade'), level: 'advanced' },
  { word: 'acquisition', arabic: 'استحواذ', example: 'The acquisition was successful.', category: 'economics', imageUrl: getImageUrl('acquisition business'), level: 'advanced' },
  { word: 'diversification', arabic: 'تنويع', example: 'Diversification reduces risk.', category: 'economics', imageUrl: getImageUrl('diversification portfolio'), level: 'advanced' },
  { word: 'equity', arabic: 'حقوق ملكية', example: 'Equity is important for investors.', category: 'economics', imageUrl: getImageUrl('equity finance'), level: 'advanced' },
  { word: 'liability', arabic: 'مسؤولية', example: 'Reduce your liabilities.', category: 'economics', imageUrl: getImageUrl('liability debt'), level: 'advanced' },
  { word: 'portfolio', arabic: 'محفظة', example: 'Review your investment portfolio.', category: 'economics', imageUrl: getImageUrl('portfolio investment'), level: 'advanced' },
  { word: 'dividend', arabic: 'أرباح', example: 'Shareholders receive dividends.', category: 'economics', imageUrl: getImageUrl('dividend money'), level: 'advanced' },
  { word: 'depreciation', arabic: 'استهلاك', example: 'Calculate the depreciation.', category: 'economics', imageUrl: getImageUrl('depreciation value'), level: 'advanced' },
  { word: 'liquidity', arabic: 'سيولة', example: 'Maintain sufficient liquidity.', category: 'economics', imageUrl: getImageUrl('liquidity finance'), level: 'advanced' },
  { word: 'volatility', arabic: 'تقلب', example: 'Market volatility is high.', category: 'economics', imageUrl: getImageUrl('volatility market'), level: 'advanced' },
  { word: 'arbitrage', arabic: 'مراجحة', example: 'Arbitrage opportunities exist.', category: 'economics', imageUrl: getImageUrl('arbitrage trading'), level: 'advanced' },
  { word: 'hedge', arabic: 'تحوط', example: 'Hedge against currency risk.', category: 'economics', imageUrl: getImageUrl('hedge finance'), level: 'advanced' },
  { word: 'leverage', arabic: 'رافعة مالية', example: 'Use leverage carefully.', category: 'economics', imageUrl: getImageUrl('leverage finance'), level: 'advanced' },

  // Philosophy & Psychology
  { word: 'consciousness', arabic: 'وعي', example: 'Consciousness is mysterious.', category: 'philosophy', imageUrl: getImageUrl('consciousness mind'), level: 'advanced' },
  { word: 'perception', arabic: 'إدراك', example: 'Perception varies by person.', category: 'philosophy', imageUrl: getImageUrl('perception mind'), level: 'advanced' },
  { word: 'cognition', arabic: 'إدراك معرفي', example: 'Cognition affects learning.', category: 'philosophy', imageUrl: getImageUrl('cognition brain'), level: 'advanced' },
  { word: 'existential', arabic: 'وجودي', example: 'Existential questions are deep.', category: 'philosophy', imageUrl: getImageUrl('existential thinking'), level: 'advanced' },
  { word: 'introspection', arabic: 'استبطان', example: 'Introspection helps self-awareness.', category: 'philosophy', imageUrl: getImageUrl('introspection reflection'), level: 'advanced' },
  { word: 'subconscious', arabic: 'لاوعي', example: 'The subconscious affects behavior.', category: 'philosophy', imageUrl: getImageUrl('subconscious mind'), level: 'advanced' },
  { word: 'rationality', arabic: 'عقلانية', example: 'Rationality guides decisions.', category: 'philosophy', imageUrl: getImageUrl('rationality thinking'), level: 'advanced' },
  { word: 'ethics', arabic: 'أخلاقيات', example: 'Ethics are fundamental in business.', category: 'philosophy', imageUrl: getImageUrl('ethics morality'), level: 'advanced' },
  { word: 'morality', arabic: 'أخلاق', example: 'Morality guides our actions.', category: 'philosophy', imageUrl: getImageUrl('morality values'), level: 'advanced' },
  { word: 'empathy', arabic: 'تعاطف', example: 'Empathy is essential in relationships.', category: 'philosophy', imageUrl: getImageUrl('empathy compassion'), level: 'advanced' },
  { word: 'resilience', arabic: 'مرونة', example: 'Resilience helps overcome challenges.', category: 'philosophy', imageUrl: getImageUrl('resilience strength'), level: 'advanced' },
  { word: 'motivation', arabic: 'دافع', example: 'Motivation drives success.', category: 'philosophy', imageUrl: getImageUrl('motivation success'), level: 'advanced' },
  { word: 'autonomy', arabic: 'استقلالية', example: 'Autonomy is valued at work.', category: 'philosophy', imageUrl: getImageUrl('autonomy independence'), level: 'advanced' },
  { word: 'ideology', arabic: 'أيديولوجية', example: 'Different ideologies exist.', category: 'philosophy', imageUrl: getImageUrl('ideology belief'), level: 'advanced' },
  { word: 'paradox', arabic: 'مفارقة', example: 'This is an interesting paradox.', category: 'philosophy', imageUrl: getImageUrl('paradox contradiction'), level: 'advanced' },

  // Science & Innovation
  { word: 'algorithm', arabic: 'خوارزمية', example: 'The algorithm is efficient.', category: 'science', imageUrl: getImageUrl('algorithm code'), level: 'advanced' },
  { word: 'biotechnology', arabic: 'تكنولوجيا حيوية', example: 'Biotechnology advances medicine.', category: 'science', imageUrl: getImageUrl('biotechnology science'), level: 'advanced' },
  { word: 'nanotechnology', arabic: 'تقنية النانو', example: 'Nanotechnology is revolutionary.', category: 'science', imageUrl: getImageUrl('nanotechnology science'), level: 'advanced' },
  { word: 'quantum', arabic: 'كمي', example: 'Quantum physics is complex.', category: 'science', imageUrl: getImageUrl('quantum physics'), level: 'advanced' },
  { word: 'genome', arabic: 'جينوم', example: 'The human genome is mapped.', category: 'science', imageUrl: getImageUrl('genome dna'), level: 'advanced' },
  { word: 'synthesis', arabic: 'تخليق', example: 'Chemical synthesis is precise.', category: 'science', imageUrl: getImageUrl('synthesis chemistry'), level: 'advanced' },
  { word: 'catalyst', arabic: 'محفز', example: 'A catalyst speeds reactions.', category: 'science', imageUrl: getImageUrl('catalyst chemistry'), level: 'advanced' },
  { word: 'hypothesis', arabic: 'فرضية', example: 'Test the hypothesis carefully.', category: 'science', imageUrl: getImageUrl('hypothesis experiment'), level: 'advanced' },
  { word: 'molecule', arabic: 'جزيء', example: 'Water is a simple molecule.', category: 'science', imageUrl: getImageUrl('molecule chemistry'), level: 'advanced' },
  { word: 'neuroscience', arabic: 'علم الأعصاب', example: 'Neuroscience studies the brain.', category: 'science', imageUrl: getImageUrl('neuroscience brain'), level: 'advanced' },
  { word: 'artificial intelligence', arabic: 'ذكاء اصطناعي', example: 'AI is transforming industries.', category: 'science', imageUrl: getImageUrl('artificial intelligence robot'), level: 'advanced' },
  { word: 'cybersecurity', arabic: 'أمن سيبراني', example: 'Cybersecurity is critical.', category: 'science', imageUrl: getImageUrl('cybersecurity security'), level: 'advanced' },
  { word: 'innovation', arabic: 'ابتكار', example: 'Innovation drives progress.', category: 'science', imageUrl: getImageUrl('innovation technology'), level: 'advanced' },
  { word: 'automation', arabic: 'أتمتة', example: 'Automation improves efficiency.', category: 'science', imageUrl: getImageUrl('automation robot'), level: 'advanced' },
  { word: 'sustainability', arabic: 'استدامة', example: 'Sustainability is our goal.', category: 'science', imageUrl: getImageUrl('sustainability green'), level: 'advanced' },

  // Communication & Language
  { word: 'articulate', arabic: 'يعبر بوضوح', example: 'Articulate your thoughts clearly.', category: 'communication', imageUrl: getImageUrl('articulate speaking'), level: 'advanced' },
  { word: 'ambiguous', arabic: 'غامض', example: 'The message was ambiguous.', category: 'communication', imageUrl: getImageUrl('ambiguous unclear'), level: 'advanced' },
  { word: 'eloquent', arabic: 'فصيح', example: 'She is an eloquent speaker.', category: 'communication', imageUrl: getImageUrl('eloquent speaker'), level: 'advanced' },
  { word: 'rhetoric', arabic: 'بلاغة', example: 'Political rhetoric is powerful.', category: 'communication', imageUrl: getImageUrl('rhetoric speech'), level: 'advanced' },
  { word: 'nuance', arabic: 'فارق دقيق', example: 'Understand the nuances.', category: 'communication', imageUrl: getImageUrl('nuance detail'), level: 'advanced' },
  { word: 'connotation', arabic: 'دلالة ضمنية', example: 'Words have connotations.', category: 'communication', imageUrl: getImageUrl('connotation meaning'), level: 'advanced' },
  { word: 'metaphor', arabic: 'استعارة', example: 'Use metaphors effectively.', category: 'communication', imageUrl: getImageUrl('metaphor language'), level: 'advanced' },
  { word: 'analogy', arabic: 'تشبيه', example: 'The analogy explains the concept.', category: 'communication', imageUrl: getImageUrl('analogy comparison'), level: 'advanced' },
  { word: 'discourse', arabic: 'خطاب', example: 'Academic discourse is formal.', category: 'communication', imageUrl: getImageUrl('discourse discussion'), level: 'advanced' },
  { word: 'persuasion', arabic: 'إقناع', example: 'Persuasion is an art.', category: 'communication', imageUrl: getImageUrl('persuasion influence'), level: 'advanced' },
  { word: 'collaboration', arabic: 'تعاون', example: 'Collaboration leads to success.', category: 'communication', imageUrl: getImageUrl('collaboration teamwork'), level: 'advanced' },
  { word: 'negotiation', arabic: 'تفاوض', example: 'Negotiation requires patience.', category: 'communication', imageUrl: getImageUrl('negotiation business'), level: 'advanced' },
  { word: 'consensus', arabic: 'إجماع', example: 'We reached a consensus.', category: 'communication', imageUrl: getImageUrl('consensus agreement'), level: 'advanced' },
  { word: 'mediation', arabic: 'وساطة', example: 'Mediation resolved the dispute.', category: 'communication', imageUrl: getImageUrl('mediation peace'), level: 'advanced' },
  { word: 'assertion', arabic: 'تأكيد', example: 'Make your assertion clear.', category: 'communication', imageUrl: getImageUrl('assertion statement'), level: 'advanced' },
]

export const COMPREHENSIVE_WORDS: WordItem[] = [
  ...BASE_WORDS,
  ...ADDITIONAL_BEGINNER_WORDS,
  ...ADDITIONAL_INTERMEDIATE_WORDS,
  ...ADDITIONAL_ADVANCED_WORDS,
]

export const CATEGORIES = [
  { id: 'greetings', name: 'التحيات', nameEn: 'Greetings', icon: '👋' },
  { id: 'family', name: 'العائلة', nameEn: 'Family', icon: '👨‍👩‍👧‍👦' },
  { id: 'food', name: 'الطعام والشراب', nameEn: 'Food & Drinks', icon: '🍕' },
  { id: 'animals', name: 'الحيوانات', nameEn: 'Animals', icon: '🐾' },
  { id: 'colors', name: 'الألوان', nameEn: 'Colors', icon: '🎨' },
  { id: 'numbers', name: 'الأرقام', nameEn: 'Numbers', icon: '🔢' },
  { id: 'body', name: 'أجزاء الجسم', nameEn: 'Body Parts', icon: '🦶' },
  { id: 'home', name: 'البيت والأثاث', nameEn: 'Home & Furniture', icon: '🏠' },
  { id: 'nature', name: 'الطبيعة والطقس', nameEn: 'Nature & Weather', icon: '🌿' },
  { id: 'time', name: 'الوقت والأيام', nameEn: 'Time & Days', icon: '⏰' },
  { id: 'education', name: 'التعليم', nameEn: 'Education', icon: '📚' },
  { id: 'transport', name: 'المواصلات', nameEn: 'Transportation', icon: '🚗' },
  { id: 'clothing', name: 'الملابس', nameEn: 'Clothing', icon: '👔' },
  { id: 'professions', name: 'المهن', nameEn: 'Professions', icon: '👨‍⚕️' },
  { id: 'verbs', name: 'الأفعال', nameEn: 'Verbs', icon: '🏃' },
  { id: 'adjectives', name: 'الصفات', nameEn: 'Adjectives', icon: '✨' },
  { id: 'business', name: 'الأعمال', nameEn: 'Business', icon: '💼' },
  { id: 'technology', name: 'التكنولوجيا', nameEn: 'Technology', icon: '💻' },
  { id: 'health', name: 'الصحة', nameEn: 'Health', icon: '🏥' },
  { id: 'travel', name: 'السفر', nameEn: 'Travel', icon: '✈️' },
  { id: 'environment', name: 'البيئة', nameEn: 'Environment', icon: '🌍' },
  { id: 'emotions', name: 'المشاعر', nameEn: 'Emotions', icon: '😊' },
  { id: 'sports', name: 'الرياضة', nameEn: 'Sports', icon: '⚽' },
  { id: 'arts', name: 'الفنون', nameEn: 'Arts', icon: '🎭' },
  { id: 'academic', name: 'أكاديمي', nameEn: 'Academic', icon: '🎓' },
  { id: 'politics', name: 'السياسة', nameEn: 'Politics', icon: '🏛️' },
  { id: 'economics', name: 'الاقتصاد', nameEn: 'Economics', icon: '📈' },
  { id: 'philosophy', name: 'الفلسفة', nameEn: 'Philosophy', icon: '🧠' },
  { id: 'science', name: 'العلوم', nameEn: 'Science', icon: '🔬' },
  { id: 'communication', name: 'التواصل', nameEn: 'Communication', icon: '💬' },
  { id: 'places', name: 'الأماكن', nameEn: 'Places', icon: '📍' },
  { id: 'weather', name: 'الطقس', nameEn: 'Weather', icon: '🌤️' },
  { id: 'relationships', name: 'العلاقات', nameEn: 'Relationships', icon: '💑' },
  { id: 'career', name: 'المهنة', nameEn: 'Career', icon: '📊' },
  { id: 'cooking', name: 'الطبخ', nameEn: 'Cooking', icon: '👨‍🍳' },
  { id: 'shopping', name: 'التسوق', nameEn: 'Shopping', icon: '🛒' },
  { id: 'entertainment', name: 'الترفيه', nameEn: 'Entertainment', icon: '🎬' },
  { id: 'personality', name: 'الشخصية', nameEn: 'Personality', icon: '👤' },
  { id: 'housing', name: 'السكن', nameEn: 'Housing', icon: '🏘️' },
  { id: 'medical', name: 'الطب', nameEn: 'Medical', icon: '⚕️' },
  { id: 'engineering', name: 'الهندسة', nameEn: 'Engineering', icon: '⚙️' },
  { id: 'language', name: 'اللغة', nameEn: 'Language', icon: '🗣️' },
  { id: 'legal', name: 'القانون', nameEn: 'Legal', icon: '⚖️' },
  { id: 'psychology', name: 'علم النفس', nameEn: 'Psychology', icon: '🧠' },
]

export function getWordsByLevel(level: 'beginner' | 'intermediate' | 'advanced'): WordItem[] {
  return COMPREHENSIVE_WORDS.filter(word => word.level === level)
}

export function getWordsByCategory(category: string): WordItem[] {
  return COMPREHENSIVE_WORDS.filter(word => word.category === category)
}

export function getWordsByCategoryAndLevel(category: string, level: 'beginner' | 'intermediate' | 'advanced'): WordItem[] {
  return COMPREHENSIVE_WORDS.filter(word => word.category === category && word.level === level)
}

export function getCategoriesWithCounts() {
  return CATEGORIES.map(cat => ({
    ...cat,
    count: COMPREHENSIVE_WORDS.filter(w => w.category === cat.id).length,
    beginnerCount: COMPREHENSIVE_WORDS.filter(w => w.category === cat.id && w.level === 'beginner').length,
    intermediateCount: COMPREHENSIVE_WORDS.filter(w => w.category === cat.id && w.level === 'intermediate').length,
    advancedCount: COMPREHENSIVE_WORDS.filter(w => w.category === cat.id && w.level === 'advanced').length,
  }))
}

export function getRandomWords(count: number, level?: 'beginner' | 'intermediate' | 'advanced'): WordItem[] {
  const words = level ? getWordsByLevel(level) : COMPREHENSIVE_WORDS
  const shuffled = [...words].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}
